### ISSUE TITLE
Disable HTTPS requirement for nodes when building Trinity

### ISSUE THREAD

**Issue by wusyong** [DLTcollab/general#101]
* On desktop:
https://github.com/iotaledger/trinity-wallet/blob/develop/src/shared/containers/settings/Node.js#L48

* On mobile:
https://github.com/iotaledger/trinity-wallet/blob/develop/src/mobile/src/ui/views/wallet/AddCustomNode.js#L192

**Comment by ender503** [comment]
Thanks, @wusyong. I disable the HTTPS checks successfully. 👍
