### ISSUE TITLE
Base: Parallelize API GTTA invocations of IRI

### ISSUE THREAD

**Issue by marktwtn** [DLTcollab/general#106]
( Initiated by @yillkid )

The IRI `getTransactionsToApproveStatement (GTTA)` is a synchronized function.
The duration becomes longer and longer with the frequent requests.

We must analyze and discuss the way to do the parallel execution.

I wrote a simple `python` script to prove the behaviour.
The script would run several threads and send the `GTTA` request to full-node.

The following are the script and the output:

Script:
```
import json
import requests
import threading
import time

COUNTS_THREAD = 10
attack_threads = []
req_body = {"command": "getTransactionsToApprove", "depth": 15}
total_duration = [None] * COUNTS_THREAD
req_url = "http://node.deviceproof.org:14265"

# Child-thread job
def job(result, index):
    headers = {'X-IOTA-API-Version':'1'}
    r = requests.post(req_url, json=req_body, headers = headers)
    print("Node URL: " + req_url + " checked hash is: " + r.text)
    result[index] = r.elapsed.total_seconds()

# Create child-threads
for i in range(COUNTS_THREAD):
    thread = threading.Thread(target=job, args=(total_duration, i))
    attack_threads.append(thread)
    thread.start()
```

Output:
```
Node URL: http://node.deviceproof.org:14265 checked hash is: {"trunkTransaction":"OGHAEVWPEVFVFI9FGUHVVSMIPAXRNNRFSNHXUMSMXVJBTFR9VZEZXLHTNCIXK9PWSR9VADWPVMXZZ9999","branchTransaction":"BKAWOQJFFUZ9ARJRF9JO9BXCBYR9BDBMKR9ZCIFUNFWYHFVLONVHUDFTVZLCKVV9KBVQAFECYVNC99999","duration":22081}
Node URL: http://node.deviceproof.org:14265 checked hash is: {"trunkTransaction":"NIGNJU9DPRIVVDIXOAFQPBGETXCLHRBHDQTONV9JOXGQSBXSRC9UAGWDVXDDHGGSVVEVRTUNFNIJZ9999","branchTransaction":"ROGJZBDCWINOPNSGOXV9GKXOIQGLVLBAOCQDTPUYTCHRDAKOWONGFHRNHOWDWQAWLXTFUHHBJSVCZ9999","duration":33568}
Node URL: http://node.deviceproof.org:14265 checked hash is: {"trunkTransaction":"SGPTXPUXRJMSOQDNIDUGFJIN9UXJSCHQIGVFMRJIVIWWKTCCCOULNACYWMAHIWP9XNUPFVTTN9AC99999","branchTransaction":"IVPJVHKTDWQIQFUEYOUXTGJJFIQQCBSKNXJXHQEFIGHPFJ9MOBLWY9DSMBUIJTQ9GNRNGUEIGJNQZ9999","duration":44039}
Node URL: http://node.deviceproof.org:14265 checked hash is: {"trunkTransaction":"DBWV9NIVE9GJCBYWYIXJQSHIPJVOEMHPBYQLHWOBOGEDCUWSQTI9NLRPTOOFEBLDSJLVYJVPZSJEA9999","branchTransaction":"VPWRZOKZTIQITAUYPBYHABPZHWIMMRBFDW9BVSRXNSCXYUMSWVPDKWTDDZXQYIGVZRNDAJFWAQVZ99999","duration":55578}
Node URL: http://node.deviceproof.org:14265 checked hash is: {"trunkTransaction":"XJSC9S9FYYF9OEUBPOQTHGKSJTYCV9QDJLRELAEYGD9LUI9NEQOWQORSCTKROUNPMBYYUAKXWAVW99999","branchTransaction":"SVZWJHUFQPL9TSCWNORDZETRZCBXQUMIQWFILMFIQNUNKYSZWLUJODJJACWDFYOIAMT9MLXGLIAM99999","duration":66470}
Node URL: http://node.deviceproof.org:14265 checked hash is: {"trunkTransaction":"RMYOWRREFLLRTNTG9ILHKRVIHYKJMUNR9FUOXKQUZBPHHQXSSJLZBHTVCSKMUESBPSTADUENUJTJ99999","branchTransaction":"USXTCHQSWHW9NLEBJETSAX9PNHCWLZGRUGZFWHFXQOWSE9BUEIVEAWW9TENVWVBYGDMIGZFWZAEPA9999","duration":78531}
Node URL: http://node.deviceproof.org:14265 checked hash is: {"trunkTransaction":"EXPBNQHYDMPKUWFESNLZIUD9LPQLLYJLKDLGDSJF9SMFXWCCEGHQUFSKXKSABTILNEMPZLEMKEGJA9999","branchTransaction":"BGCIUWMVESPVXVKHCDAEQ9GZJHGUHMRIURE9NRNBGUVLJZZEVNZFYVTYDWASCZDHKLJKWVPLMCKB99999","duration":92229}
Node URL: http://node.deviceproof.org:14265 checked hash is: {"trunkTransaction":"XMRTNWM9LHXNUZFWVNPCEQKLF9IUEYXJRYIEWKYVWDGJKNGOKF99UYWZYYTSLJSRNMVBABMUHEHAZ9999","branchTransaction":"KDAONVTQYTNCDKQRUYPC9KCBGLQPJZPNFCOYELUOJULBKKMQLYMWHUIGL9WIOLCUJBQXLVTQ9EDUZ9999","duration":104238}
Node URL: http://node.deviceproof.org:14265 checked hash is: {"trunkTransaction":"KDXVXRGZMSPRSYFMWSH9LMWPA9XTGCKB9NUPZXWWJSYFUHKXYMHMFUKZUFGZVQNUXE9GJSTQAWJ9Z9999","branchTransaction":"DPUGPTGMXQAWQDYVCYRPRIE9SFACIXLALASYUTHTYWDDTNINOYMVVTOPWOHWHAQTLTLSRHSS9YBAZ9999","duration":115886}
Node URL: http://node.deviceproof.org:14265 checked hash is: {"trunkTransaction":"BGCIUWMVESPVXVKHCDAEQ9GZJHGUHMRIURE9NRNBGUVLJZZEVNZFYVTYDWASCZDHKLJKWVPLMCKB99999","branchTransaction":"WKINZTZRJMNC9BZXUKRNZUVYUFUPYGKJVPHDSWDDANZEKWTCZDJAIRRPMWPOWRAZGGOQCVZSWXMHA9999","duration":128288}
```

**Reference:**
```
    Discord

< YuWei Wu > I want to rephrase the quiestion above to see if anyone can answer.
What is the reaseon to use synchronized in getTransactionsToApproveStatement?
Does hercules also implement the same way?

< Gal Rogozinski [IF] > Calculating cumulative weight (part of tip selection) is a heavy operation and we don't want the node to be dosed. Still, the synchronized itself shouldn't be in the API layer.
Anyhows, we may enable parallel tip selection in the future

See https://github.com/iotaledger/iri/issues/973
```

- [Test parallel calls to GTTA #973](https://github.com/iotaledger/iri/issues/973)

---

Experiment result of different IRI testnet
marktwtn:

The IRI testnets are run on the `devorg` device.
The difference is the existence of the `GTTA` **synchronized** keyword.
The testnets are all fully-synced. (The `latestMilestone` and the `latestSolidSubtangleMilestoneIndex` are the same)
However, the `latestMilestone` of the **non-synchronized** testnet is not the newest.
It causes the return tips value of `getNodeInfo` API is zero, and the `getTips` API does not return any tip.
But `getTransactionsToApprove` API do return trunk and branch transaction.

The following charts are the experiment result of using `jMeter` to send `GTTA` http request to the testnets.

IOTA IRI v1.5.3
![gtta parallel test on testnet2](https://user-images.githubusercontent.com/6748200/48885087-f71e5a00-ee61-11e8-8c9a-9bfdc244ddbd.png)

without `synchronization` keyword - DLTLab IRI
![gtta parallel test on testnet1](https://user-images.githubusercontent.com/6748200/48885045-d524d780-ee61-11e8-8048-fb6b178a9a21.png)

The black dots represent the response time of each `GTTA` and the green dots represents the throughput.
They are better in the **non-synchronized** testnet.

To-do:
1. Observe the used calculation resource.
2. [Test parallel calls to GTTA #973](https://github.com/iotaledger/iri/issues/973) mentioned that
```
Are milestones still being updated as the calls come in?
```
Since it had been fully-synced already, I have no idea about how to deal with the question.

**Comment by marktwtn** [comment]
Here comes the experiment result with the `testnets` updating to the newest milestone and being fully-synced.

IOTA IRI v1.5.3
![gtta parallel test on testnet - 2](https://user-images.githubusercontent.com/6748200/49341653-b4435a00-f68b-11e8-88af-bce1b56d8c21.png)

DLTLab IRI - without `synchronization` keyword
![gtta parallel test on testnet](https://user-images.githubusercontent.com/6748200/49341655-b86f7780-f68b-11e8-8370-8ddb057f336b.png)

@Citrullin The labels in the images had been changed to the English.

**Comment by yillkid** [comment]
Will you plan to move all the testing to the `mainnet` network? You need a testing full-synced IRI on `mainnet`, right?

**Comment by marktwtn** [comment]
The following charts are the resource consumption while sending the `GTTA` http request 1000 times at the same time.

IOTA IRI v1.5.3
(`GTTA` request 1000 times) x 2
![iri-testnet-1](https://user-images.githubusercontent.com/6748200/49527573-2e264e00-f8ed-11e8-87f7-39404a3274bc.png)

DLTLab IRI - without `synchronization` keyword
(`GTTA` request 1000 times) x 7
![no-sync-3](https://user-images.githubusercontent.com/6748200/49527588-34b4c580-f8ed-11e8-9da0-fddeff847c57.png)

Without `synchronization` keyword, the CPU and used heap do increase while handling the `GTTA` requests.

If the resource consumption is acceptable, the last question is:
```
Are milestones still being updated as the calls come in?
```

**Comment by marktwtn** [comment]
The `latestSolidSubtangleMilestone` would not be updated if there are lots of `GTTA` coming in a short period.

**milestone**
MilestoneTracker.java
```
void updateLatestSolidSubtangleMilestone() throws Exception {
...
ledgerValidator.updateSnapshot(milestoneViewModel)
...
}
```
LedgerValidator.java
```
public boolean updateSnapshot(MilestoneViewModel milestoneVM) throws Exception {
milestoneTracker.latestSnapshot.rwlock.writeLock().lock();
...
milestoneTracker.latestSnapshot.rwlock.writeLock().unlock();
}
```

**GTTA**
TipSelectorImpl.java
```
public List<Hash> getTransactionsToApprove(int depth, Optional<Hash> reference) throws Exception {
milestoneTracker.latestSnapshot.rwlock.readLock().lock();
...
milestoneTracker.latestSnapshot.rwlock.readLock().unlock();
}
```

The update of milestone uses write lock, while `GTTA` uses read lock.
Hence if there are intensive `GTTA` requests coming, the milestone(latest solid subtangle) would not be updated.

**Comment by marktwtn** [comment]
There are two behaviour I observed:

1.
The performance looks promising.
However, if the total GTTA requests are too many and sent at the same time, there would be some requests never be responded.

(In our full-node, it would be around 4000 requests.)

2.
The returned trunk and branch transactions would be referenced by the future milestone.
The transactions of the original version look fine.
But the transactions of the **no-sync** version are weird.
Most of the transactions are duplicated.

The ratio of the duplicated returned transaction:
Original: 85/1000
No-sync: 873/1000

It is probably caused by the time, since the **no-sync** version response faster than the original version.
In a short period of time, the returned transactions seems to have a great possibility to be duplicated.

**Comment by jserv** [comment]
Cc. @wusyong

**Comment by marktwtn** [comment]
> Hence if there are intensive `GTTA` requests coming, the milestone(latest solid subtangle) would not be updated.

Change the readWriteLock to `fair mode` may solve the problem.
The `fair mode` would let the longest waiting thread to get the lock first.

I will use the `jMeter` to send intensive `GTTA` requests,
make sure the milestone won't update and change the lock to `fair mode` to see the result.

**Comment by jserv** [comment]
@marktwtn, do we have to configure acquire timeout for readWriteLock manually?

**Comment by marktwtn** [comment]
Under the intense `GTTA` requests with `jMeter`

1. There are failed requests because of the `connection timeout(can not setup connection)` or `connection reset(does not get response data)`.
2. The milestone updates normally.

The limitation of IRI handling the http requests makes it hard to do the intense `GTTA`.
However, if we do not consider the ability of handling the http requests, the milestone does be updated successfully even if it handles the maximum `GTTA` requests it can get.

**The milestones are still updated as the GTTA calls come in.**

---

> @marktwtn, do we have to configure acquire timeout for readWriteLock manually?

Base on the above description, we might not have to worry about this.

**Comment by marktwtn** [comment]
Here is the brief conclusion.

The performance of GTTA is better when the **synchronized** keyword is removed.
GTTA is thread safe by using the Java `readWriteLock`.
We do not bother from the lock contention since the milestone update (write lock) happens every 30 sec to 1 min.
Even under the intense GTTA requests coming, the milestone is updated normally.

I have updated the result in [Test parallel calls to GTTA #973](https://github.com/iotaledger/iri/issues/973)
and create the pull request [Parallelize GTTA API #1245](https://github.com/iotaledger/iri/pull/1245).

If there isn't any problem, I think we can close this issue.

**Comment by jserv** [comment]
Let's update `dev-rebase` branch to reflect this change along with full nodes we maintain.

**Comment by jserv** [comment]
Transition to IF upstream.
