### ISSUE TITLE
Base: Trace MAM

### ISSUE THREAD

**Issue by jkrvivian** [DLTcollab/general#108]
We will trace [MAM/v2](https://github.com/iotaledger/entangled/tree/develop/mam) to see if we can relay the calculation of merkle tree to tangle accelerator.

**Comment by wusyong** [comment]
Example of mam v2: [both send and receive](https://github.com/iotaledger/entangled/tree/develop/mam/v2/examples)

**Comment by wusyong** [comment]
Some [notes ](https://hackmd.io/s/HkFNQCO_4)from @HowJMay

**Comment by wusyong** [comment]
Some [notes ](https://hackmd.io/s/HkFNQCO_4)from @HowJMay
