### ISSUE TITLE
dcurl: Integrate with bazel 

### ISSUE THREAD

**Issue by wusyong** [DLTcollab/general#109]
Due to tangle-accelerator dependency and also consider supporting entangled in the future, we should integrate dcurl into bazel. Right now we have two options:

* Edit BUID files in tangle_accelerator
* Support bazel directly in dcurl repo

**Comment by jkrvivian** [comment]
We also have an issue in tangle-accelerator, [Core: Import dcurl](https://github.com/DLTcollab/tangle-accelerator/issues/1)

**Comment by wusyong** [comment]
Consider we are going to integrate dcurl to entangled, I would prefer making dcurl repo support dcurl directly (or at least a branch).

**Comment by wusyong** [comment]
The choice is add BUILD files in tangle-accelerator. Further discussion goes to [Core: Import dcurl](https://github.com/DLTcollab/tangle-accelerator/issues/1)
