### ISSUE TITLE
Base: packaging IRI + dcurl with our customizations

### ISSUE THREAD

**Issue by jserv** [DLTcollab/general#110]
We would like to invite our partners such as Laboratory for Machine Tools and Production Engineering (WZL) of RWTH Aachen to take our customized IRI for better performance and scalability. However, the current build process is a bit confusing, and we might introduce a straightforward way to execute "make all" and/or "make check" without having to care about different build systems.

Here is my proposal against IRI:
1. Prepare a dedicated `Makefile`, which provides necessary targets to build rocksdb, dcurl, and other dependency from scratch.
2. Run `mvn install:install-file -Dfile=rocksdbjni-${ROCKSDB_VERSION}-linux64.jar -DgroupId=org.rocksdb -DartifactId=rocksdbjni -Dversion=${ROCKSDB_VERSION} -Dpackaging=jar` for configuring rocksdbjni
3. Build dcurl with AVX2 enabled (check CPU features at build time).
4. Run `mvn -q clean compile` and `mvn -q package -Dmaven.test.skip`
5. (Optional) Invoke test suites and validate

**Comment by jserv** [comment]
Reference: https://github.com/muXxer/rock64-docker-iota-fullnode/blob/master/dockerfiles/Dockerfile_iri

**Comment by jserv** [comment]
Related: #106

**Comment by marktwtn** [comment]
I have created a Makefile in IRI, it does the following things:

1. Download the repositories of rocksdb and dcurl, then build them.
- dcurl
  If the hardware does not support AVX2, it would use AVX instead.
- rocksdb
  The current rocksdb can not be built successfully without some modifications.
    - rocksdb Makefile
      `BZIP2_DOWNLOAD_BASE ?= http://www.bzip.org -> https://web.archive.org/web/20180624184835/http://www.bzip.org`
    - util/crc32c.cc
      The source code uses `#ifdef HAVE_SSE42` or `#if defined(__SSE4_2__)` at the different lines.
      Somehow the `#ifdef HAVE_SSE42` does not take effect, I use the latter instead.
      I will find out the reason then.

2. Run `mvn install:install-file ...` to install the rocksdb jar in the local repository.
3. Build IRI

**Comment by jserv** [comment]
> * rocksdb
>   The current rocksdb can not be built successfully without some modifications.

Send pull request(s) to RocksDB for the review from Facebook's engineering team.
Prepared patch against rocksdb could be acceptable during build process.

**Comment by marktwtn** [comment]
> > * rocksdb
> >   The current rocksdb can not be built successfully without some modifications.
> 
> Send pull request(s) to RocksDB for the review from Facebook's engineering team.
> Prepared patch against rocksdb could be acceptable during build process.

Sorry for my bad description.
"The current rocksdb" means the rocksdb repository of DLTCollab.
I use `BUILD.sh` to build it.

The official rocksdb repository has not been tested for building by me.
But I'm sure the `BZIP2_DOWNLOAD_BASE` variable of the official rocksdb is correct.

**Comment by jserv** [comment]
> I have created a Makefile in IRI, it does the following things:
> 1. Download the repositories of rocksdb and dcurl, then build them.
> 2. Run `mvn install:install-file ...` to install the rocksdb jar in the local repository.
> 3. Build IRI

The feature is absent in branch `dev-rebase`. We have to automate the build process and prepare elegant ways to deploy JAR file + native library as well.

**Comment by jserv** [comment]
Related: #123

**Comment by jserv** [comment]
Preliminary work was verified. I'll invite WZL of RWTH Aachen for trial. Cc. @yillkid and @lmanchu
