### ISSUE TITLE
Base: RocksDB tweaks

### ISSUE THREAD

**Issue by jserv** [DLTcollab/general#111]
There are some community efforts to introduce RocksDB tweaks as following:
* [IRI + RocksDB 5.17](https://github.com/iotaledger/iri/pull/1206/files)
* [RocksDB thread options](https://github.com/iotaledger/iri/pull/405)
* [Parallel reading and writing](https://github.com/iotaledger/iri/issues/1006)
* [Improve performance when reading long values from the DB](https://github.com/iotaledger/iri/issues/928)

We would like to integrate and rework these preliminary work for our custom build. Once they are verified, we might contribute back to the community.

**Comment by jserv** [comment]
Release branch [5.18.fb](https://github.com/facebook/rocksdb/commits/5.18.fb) is what we concentrate on.

**Comment by jserv** [comment]
Highlight [upstream RocksDB features](https://github.com/facebook/rocksdb/blob/5.18.fb/HISTORY.md), which would be effective to IRI from the perspective of overall performance:
* jemalloc: [scalable memory allocator](https://www.facebook.com/notes/facebook-engineering/scalable-memory-allocation-using-jemalloc/480222803919/)
* ZSTD dictionary trainer: better compression ratio
* Add a new tool: trace_analyzer, which analyzes the trace file generated by using trace_replay API. It can convert the binary format trace file to a human readable txt file, output the statistics of the analyzed query types such as access statistics and size statistics, combining the dumped whole key space file to analyze, support query correlation analyzing, and etc.
* Introduced CompressionOptions::kDefaultCompressionLevel, which is a generic way to tell RocksDB to use the compression library's default level. It is now the default value for CompressionOptions::level. Previously the level defaulted to -1, which gave poor compression ratios in ZSTD.
* Improve the performance of iterators doing long range scans by using readahead.
* Add new function DeleteFilesInRanges() to delete files in multiple ranges at once for better performance.
* Improved performance of long range scans with readahead.
* CRC32C is now using the 3-way pipelined SSE algorithm crc32c_3way on supported platforms to improve performance. The system will choose to use this algorithm on supported platforms automatically whenever possible. If PCLMULQDQ is not supported it will fall back to the old Fast_CRC32 algorithm.

**Comment by jserv** [comment]
A comprehensive Chinese article about RocksDB: [RocksDB 筆記](https://hk.saowen.com/a/6140aaf77263ce04881b5e24d4f47a3de1c772fae5da1f0405e3997521034755).

**Comment by marktwtn** [comment]
The pull request of [IRI + RocksDB 5.17](https://github.com/iotaledger/iri/pull/1206/files) works well on rocksdb 5.18.0 with small modification.
Except those having been fixed in the pull request, there are no other deprecated functions used in IRI.
I setup a mainnet on device `node10` with IRI + rocksdb 5.18.0.
It seems no problems at all.

IF says that after doing the proper tests, they will merge this pull request.
I think we can patch our modification first and rebase DLTCollab IRI after they merge the pull request.

---
[RocksDB thread options](https://github.com/iotaledger/iri/pull/405)
The pull request contains multiple subjects and should be separated.
One of the subject is reinterrupting the threads after an InterruptedException is thrown.
However, it does not seem to come with agreement with the reviewers.
I will send a pull request of the rest subjects.

**Comment by jserv** [comment]
Related: #116

**Comment by jserv** [comment]
Right now, [our custom IRI](https://github.com/dltcollab/iri) supports RocksDB v5.18.x

**Comment by marktwtn** [comment]
> [RocksDB thread options](https://github.com/iotaledger/iri/pull/405)
> The pull request contains multiple subjects and should be separated.
> One of the subject is reinterrupting the threads after an InterruptedException is thrown.
> However, it does not seem to come with agreement with the reviewers.
> I will send a pull request of the rest subjects.

The rest of the pull request is mainly for code refinement.
Since this pull request has been postponed for a year(2017/12),
the modifications are useless.
RocksDB has already included these modifications with a better and elegant version.

**Comment by marktwtn** [comment]
The last two issues:

* [Parallel reading and writing](https://github.com/iotaledger/iri/issues/1006)

    The parallel reading and writing had been implemented in the default features of `rocksDB`.
Hence the problem should be focusing on how to make read from `rocksDB` has better performance.
The conclusion is we need to change the configuration like thread number to improve it.

    The performance after changing will be measured with the benchmark in the following link:
[Profile the rocksDB performance in deleting, fetching and writing](https://github.com/iotaledger/iri/issues/924)

* [Improve performance when reading long values from the DB](https://github.com/iotaledger/iri/issues/928)

    The problem is that reading long values from `rocksDB` (may) get stuck.
Here comes with two solutions:
1. Call method `setMergeOperatorName("stringappendtest")`, which loads large value to memory at once.
2. Modify and apply PR [#401](https://github.com/iotaledger/iri/pull/401), which loads partial values multiple times.

    It seems that `IF` prefer solution 2.
    I am not sure about loading large value to memory at once would be a problem or not.

**Comment by marktwtn** [comment]
The conclusion of **RocksDB thread options** pull request:

There are three subjects in the pull request.
1. Add re-interruption but does not affect the thread execution.
2. Close resource in the removed Java file.
3. Code refinement which had been integrated into IRI.

I suggest that this pull request can be closed without merging.
The more detailed explanation is recorded in the [comment](https://github.com/iotaledger/iri/pull/405#issuecomment-454468707).

**Comment by jserv** [comment]
RocksDB `v6.1.2` is the latest release. We shall consider to align with RocksDB `v6.1` branch.

**Comment by kwek20** [comment]
Hi @jserv and @marktwtn , id like to work with you get these features merged back into IRI! Do you have a discord account I can talk to?

**Comment by marktwtn** [comment]
> Hi @jserv and @marktwtn , id like to work with you get these features merged back into IRI! Do you have a discord account I can talk to?

@kwek20 my discord ID is `marktwtn#4587`.

**Comment by jserv** [comment]
We would focus on HORNET rather than IRI.
