### ISSUE TITLE
Base: incorporate IRI v1.5.6 and deploy

### ISSUE THREAD

**Issue by jserv** [DLTcollab/general#112]
The changes of IRI release version 1.5.6 have been merged into `dev` branch, and it is time to incorporate and deploy to all nodes we maintain for both mainnet and testnet.

**Comment by jserv** [comment]
It is crucial to take global snapshot as well. Cc. @yillkid

**Comment by marktwtn** [comment]
The IRI now releases the version 1.6.0.

Shall we close the issue and open another one for v1.6.0,
or just change the title and I can record the incorporation of v1.6.0 here?

**Comment by jserv** [comment]
Let's split local snapshots (LS) specific issues into dedicated ones.
