### ISSUE TITLE
Base: The behavior of cliri in Sync.

### ISSUE THREAD

**Issue by KevinKu** [DLTcollab/general#113]
Problem:[Define how to know if a node is in sync.](https://github.com/iotaledger/cliri/issues/13)

We need an article how to do sync in cliri.

[The behavior of cliri in Sync.](https://hackmd.io/s/BkwzEMCgV)

**Comment by jserv** [comment]
FYI: https://www.trias.one/article/287
> DAG 完成去 COO 的 V1 開發

Repository of Trias Lab: https://github.com/trias-lab/iri/commits/dev

**Comment by KevinKu** [comment]
I add section which I said last week.

[The behavior of cliri in Sync.](https://hackmd.io/s/BkwzEMCgV)
