### ISSUE TITLE
Base: RocksDB performance tuning and result comparison

### ISSUE THREAD

**Issue by marktwtn** [DLTcollab/general#116]
In RocksDB, there are several configuration options being used for performance tuning.
For example, the compression algorithm can be changed for less main memory usage.

I would start from changing the compression algorithm and record the value of CPU, main memory and hard disk usage.

RocksDB wiki reference:
[Setup Options and Basic Tuning](https://github.com/facebook/rocksdb/wiki/Setup-Options-and-Basic-Tuning)
[RocksDB Tuning Guide](https://github.com/facebook/rocksdb/wiki/RocksDB-Tuning-Guide)

**Comment by marktwtn** [comment]
Base on the recommendation of the [rocksDB wiki](https://github.com/facebook/rocksdb/wiki/Compression), I changed the compression algorithm to `Zstd`.
```
If you want to further reduce the in-memory and have some free CPU to use,
you can try to set a heavy-weight compression in the latter
by setting options.bottommost_compression.
...
We recommend ZSTD.
```

CPU - observed with command `ps -p <pid> %cpu`, unit: %
main memory - observed with command `ps -p <pid> %mem`, unit: %
hard disk - observed with command `$ du -h <directory>`

---

Here are some issues to be mentioned:
1. We can not create two mainnets on the device `node10` at the same time.
Hence the experiment would be setting up the mainnet one at a time and measure the performance.

2. Restarting the mainnet decreases the main memory usage.
I won't measure the performance unless the mainnet is fully-synced, which may take some time.

3. [Profile the rocksDB performance in deleting, fetching and writing](https://github.com/iotaledger/iri/issues/924)
`IRI` offers a benchmark to show the operation performance of rocksDB.
But it takes a long time to complete and it should be executed on the machine without other extra processes running.

4. Measure CPU load.
It is weird that the CPU load result of tool `jvm-mon` and command `ps -p <pid> %cpu` are totally different.
One is around 5 ~ 10% and the other is 90 ~ 95%.

**Comment by jserv** [comment]
Let's stick on HORNET's development.
