### ISSUE TITLE
Trace IRI

### ISSUE THREAD

**Issue by KevinKu** [DLTcollab/general#117]
For feature experiment , I not only  trace cliri but also trace IRI.
I record key part of IRI .

[Trace IRI](https://hackmd.io/s/Hy8de87zE)

**Comment by KevinKu** [comment]
Fix view of 12/13.

[1/17](https://hackmd.io/s/Skk06luAQ#117)

**Comment by KevinKu** [comment]
Record how to generate doc.

[產生doc](https://hackmd.io/s/Hy8de87zE#產生doc)

**Comment by jserv** [comment]
Concentrate on detailed sub-tasks.
