### ISSUE TITLE
Improve data integrity for sensors via hardware-assisted signing and verification

### ISSUE THREAD

**Issue by ajblane** [DLTcollab/general#122]
I assume we prefer to care sensor data reliability and not care that adversary steals sensor data in our IOTA applications. we identify signed data as data reliability. However, we need to provide some techniques to resist some attacks, e.g. driver rootkit attack. In this assumption, we do not port sensor driver from REE to TEE.  To ensure sensor data reliability, we need to sign sensor data by TA, run signed sensor driver and provide a tool to hook driver interface for sensor data into TEE not into user space in REE as the following depict:

![image](https://user-images.githubusercontent.com/5338746/58398603-2d929700-8088-11e9-9372-6e6cd56497d6.png)

Some techniques:
* disable /dev/mem in order to not access physical memory in user space
* build program whitelist in order to not run unsigned drivers and unsigned user programs and can refer to the Shadow-Box project, https://github.com/kkamagui/shadow-box-for-arm
* Over-The-Air management of Secure Keys and Trusted Application (TA), as refers to #151

If adversary bypasses these techniques to steal sensor data, these sensor data are identified as not reliability in our IOTA applications.

**Comment by jserv** [comment]
TODO: prepare proposal to OpenFog Security WG

**Comment by ajblane** [comment]
## Open Trusted Protocol
* OPTEE/ Intel SGX
* [Visual Studio 15](https://github.com/dthaler/OTrP/blob/master/OTrP.sln)
* vexpress-qemu_armv8a
* Receiving a request to install a new Trusted Application
![image](https://user-images.githubusercontent.com/5338746/58777961-401a4c80-8603-11e9-9b2b-50c3b780175c.png)

**Comment by ajblane** [comment]
For [dthaler/OTrP](https://github.com/dthaler/OTrP), it runs on Windows OS and links Microsoft library for the REE part, e.g.: httpapi.lib. Therefore, we need to port dthaler's OTrP project form Windows to Linux.

**Comment by jserv** [comment]
We have an internal project, named T-REE. Close this for concentrating and moving on.
