### ISSUE TITLE
Base: Load balancing for Tangle-accelerator

### ISSUE THREAD

**Issue by yillkid** [DLTcollab/general#127]
Balancing the Tangle-accelerator requests from mobile applications and IoT devices and IOTA full-node broadcast request from Tangle-accelerator followed by a brief description:

![arc_iri_load_balancer 1](https://user-images.githubusercontent.com/185872/52696763-c8b8a280-2faa-11e9-9885-4fa565213db9.png)

The load balancer improves the distribution of workloads across multiple computing endpoints, such as mobile applications and IoT devices.

## Expected Functionality
* Forward all Tangle-accelerator and full-node APIs
* HTTPS protocol support
* Node health checks

#### IOTA full-node
- Host
  - node0.puyuma.org:8002
- Providers
  - `https://node.deviceproof.org:443`
  - `http://potato.iotasalad.org:14265`
  - `http://durian.iotasalad.org:14265`
  - `http://peanut.iotasalad.org:14265`
  - `http://tuna.iotasalad.org:14265`
  - `http://turnip.iotasalad.org:14265`

#### Tangle accelerator
WIP

## TODO
- [x] Providers for Tangle-accelerator
- [x]  Node health checks, issue [#123](https://github.com/DLTcollab/general/issues/123)

**Comment by yillkid** [comment]
Tangle-accelerator available on ```http://node0.puyuma.org:8003```

Backend
```
upstream ta_mainnet {
        server node.deviceproof.org:5556;
        server node10.puyuma.org:5556;
        server node1.puyuma.org:5556;
}
```

**Comment by jserv** [comment]
At the moment, the host name of load balancer is changed to `tangle.biilabs.io`.
