### ISSUE TITLE
Base: Avoid MAM transactions not confirmed

### ISSUE THREAD

**Issue by ender503** [DLTcollab/general#130]
The transactions of MAM messages may keep pending and not be confirmed, and it comes to uncertainty since the sender can not invalidate specific MAM stream.

To make these MAM transaction confirmed, we need to find an appropriate way to reattached these transactions.

**Comment by ender503** [comment]
https://www.reddit.com/r/Iota/comments/agd5u5/psa_unconfirmed_data_mam_transactions_are_not/

**Comment by KevinKu** [comment]
I think this issue should be closed.

This is [reason](https://hackmd.io/s/BkwVNoMH4?fbclid=IwAR2lqSo3hVs8qgk0FMtFP_nfziwp2d0b0Sx2jTCEYqqNJZ_yrqZ-VBFtEFg).
