### ISSUE TITLE
Base: append explicit version information to IRI

### ISSUE THREAD

**Issue by jserv** [DLTcollab/general#131]
Since we already build a customized variant of IRI to accelerate certain operations, it would be necessary to distinguish the original build (so called [vanilla](https://wiki.debian.org/vanilla) in Linux kernel) and our customized one, otherwise it causes problems for deployment.

Expected output:
1. Generate final package as `iri-1.6.0-COACH` rather than `iri-1.6.0-RELEASE`. Here "coach" means [coachbuilder](https://en.wikipedia.org/wiki/Coachbuilder);
2. Launching messages in `iri-1.6.0-COACH` shall contain words like `coach-built by DLTcollab - https://github.com/DLTcollab`;

**Comment by jserv** [comment]
Cc. @yillkid, it should be informative for your deployment scripts.

**Comment by marktwtn** [comment]
The expected output 1 has been achieved with the new commit of our IRI.

**Comment by jserv** [comment]
Verified and deployed.
