### ISSUE TITLE
Base: Package IRI + dcurl jar file and use the dcurl library correctly

### ISSUE THREAD

**Issue by marktwtn** [DLTcollab/general#136]
Based on the issue: https://github.com/DLTcollab/dcurl/issues/106, `dcurl` can generate the jar file of library easily.

However, to use the `dcurl` library successfully, the `IRI` dependency configuration file and source code should be modified as well.

Expected output:
- `pom.xml`: add the dependency of `dcurl` jar file.
- `PearlDiver.java`: load the `dcurl` library successfully. (We can reference the loading steps from `rocksdb`)
- `Makefile`: generate and install the `dcurl` jar file in local maven repository.

**Comment by marktwtn** [comment]
Although the loading steps of `rocksdb` seems useful, it can not be applied to our `dcurl`.
The reason is:
`rocksdb`
The jar file includes the `rocksdb` classes and the shared library.
The loading steps are written in the classes, and the skill it uses must require the classes and the library to be together in the jar file.
`dcurl`
The jar file only includes the shared library.

Unless it is acceptable to create a Java file in `dcurl`, otherwise I will try another way to implement the loading steps.
For example, there are some jar file related methods.

**Comment by marktwtn** [comment]
The issue can be closed since the implementation is done in the pull requests [#3](https://github.com/DLTcollab/iri/pull/3) and [#141](https://github.com/DLTcollab/dcurl/pull/141).

**Comment by jserv** [comment]
Checked.
