### ISSUE TITLE
Base: Evaluate the service to receiving the alert messages from AlertManager

### ISSUE THREAD

**Issue by ender503** [DLTcollab/general#139]
Since the Prometheus alert manager will send the alert messages when service is broken, we need a service to receives these message to trigger the scripts to restart the broken service automatically.

Since Prometheus can be integrated with the following services, we could consider them.
https://victorops.com
https://www.pagerduty.com
https://www.opsgenie.com

**Comment by ender503** [comment]
@yillkid find out a service named RUNDECK.
It looks pretty well to manage Ansible scripts with a beautiful user interface.
But I don't know how it could be integrated with AlertManager, please give me more information, thanks. 😃 

See also: https://www.rundeck.com/ansible

**Comment by ender503** [comment]
@yillkid you could change this issue as you like, the modification is welcome. 👍

**Comment by yillkid** [comment]
Evaluating [RUNDECK](https://www.rundeck.com/what-is-rundeck):

## Standard Operating Procedures
![image](https://user-images.githubusercontent.com/185872/55211272-33096780-5226-11e9-8638-3bb2a3dee8d7.png)
![image](https://user-images.githubusercontent.com/185872/55211275-36045800-5226-11e9-84e2-89be6e20b0f3.png)
![image](https://user-images.githubusercontent.com/185872/55211285-3866b200-5226-11e9-8288-717ff08cf5a6.png)
![image](https://user-images.githubusercontent.com/185872/55211286-3b61a280-5226-11e9-9c9b-639adca00a24.png)
![image](https://user-images.githubusercontent.com/185872/55211289-3dc3fc80-5226-11e9-8554-786d96d2dd70.png)

## Dashboard
![image](https://user-images.githubusercontent.com/185872/55211299-46b4ce00-5226-11e9-8ae9-9138279c1a92.png)

## Basic usage

#### Integrate Rundeck with deploy script
![0](https://user-images.githubusercontent.com/185872/55217335-3dcdf780-523a-11e9-99f7-08c187781116.png)

#### Integrate Rundeck with Ansible playbook
![1](https://user-images.githubusercontent.com/185872/55217358-4faf9a80-523a-11e9-80bf-0b6f167e3924.png)

#### Node Execution
- [SSH](https://docs.rundeck.com/docs/administration/projects/node-execution/ssh.html)

#### Job
- Creating jobs
    - [Creating a job GUI](https://docs.rundeck.com/docs/manual/creating-jobs.html)
- Running a Job
  - [REST API](https://docs.rundeck.com/docs/api/#running-a-job)

## Rundeck ansible integration
![image](https://user-images.githubusercontent.com/185872/55211362-98f5ef00-5226-11e9-8d69-e06271fc2833.png)

## Reference
- [Rundeck](https://www.rundeck.com/)
- [Rundeck makes Ansible even better](https://www.rundeck.com/ansible)
- [RunDeck——Web界面的運維控制台](https://my.oschina.net/fitnessefan/blog/425682)

**Comment by yillkid** [comment]
> @yillkid find out a service named RUNDECK.
> It looks pretty well to manage Ansible scripts with a beautiful user interface.
> But I don't know how it could be integrated with AlertManager, please give me more information, thanks. 
> 
> See also: https://www.rundeck.com/ansible

#### Integrate Rundeck with deploy script
![0](https://user-images.githubusercontent.com/185872/55217335-3dcdf780-523a-11e9-99f7-08c187781116.png)

#### Integrate Rundeck with Ansible playbook
![1](https://user-images.githubusercontent.com/185872/55217358-4faf9a80-523a-11e9-80bf-0b6f167e3924.png)

#### Refer the documentation as below:
- Rundeck official documentation
  - Creating jobs
      - [Creating a job GUI](https://docs.rundeck.com/docs/manual/creating-jobs.html)
  - Running a Job
    - [REST API](https://docs.rundeck.com/docs/api/#running-a-job)
- [Rundeck makes Ansible even better](https://www.rundeck.com/ansible)

**Comment by ender503** [comment]
Rundeck can be an alternative solution of Ansible or Integrated with Ansible.
I'll prefer to integrate it with Ansible if we are going to use it.
Because Rundeck manages its scripts with the website interface, it will be hard to move to another solution if someday we don't want to use it.

**Comment by ender503** [comment]
To use the Rundeck with the AlertManager, we could use the [routes](https://prometheus.io/docs/alerting/configuration/#route) section to define which alert message should be sent to which `receiver`, then each `receiver` will point to the [Rundeck job API](https://docs.rundeck.com/docs/api/#running-a-job).

**Comment by yillkid** [comment]
A [simple Rundesk deploy note (WIP)](https://hackmd.io/s/BJblNdlt4)

**Comment by yillkid** [comment]
Finish all evaluate work, I will create the other issue for deploy rundesk to node0  and write the first Ansible job.
