### ISSUE TITLE
Base: Data Type Definition

### ISSUE THREAD

**Issue by ender503** [DLTcollab/general#145]
| Project            | Name         | Subject          | Exchange / Storage | Data Format                                       | Signature                            | Description                                                |
| ------------------ | ------------ | ---------------- | ------------------ | ------------------------------------------------- | ------------------------------------ | ---------------------------------------------------------- |
| TangleID           | DID Document | Human/IoT Device | On-chained         | JSON-LD                                           | Linked-Data Signature                | Describe identity’s public keys and authentication method. |
| TangleID           | Credentials  | Human            | Off-chained        | JSON-LD                                           | Linked-Data Signature                | Describe identity's properties.                            |
| TangleID           | IoT Data(?)  | IoT Device       | On-chained         | JSON-LD                                           | Linked-Data Signature                |                                                            |
| Tangle Accelerator | IoT Data(?)  | IoT Device       | On-chained         | Custom Format, e.g. JSON, XML, Protocol Buffer... | Custom Signature, e.g. RSA Signature |                                                            |

**Comment by wusyong** [comment]
Could Iot data viewed as recipient?
