### ISSUE TITLE
Evaluate utilities to compile solidity contract

### ISSUE THREAD

**Issue by ender503** [DLTcollab/general#148]
To implement the Deploy Contract API in #146, we need to evaluate utilities to compile the solidity contract.

**Comment by ender503** [comment]
Let the user compile the contract locally will be tough, and we'll need to tell the user how to compile the contract and suggest which solidity compiler that we recommend.

**Comment by ender503** [comment]
Since the `byte code` and `ABI interface` are large, sending these large data to API will cost lots of time. 🤔

**Comment by jserv** [comment]
IMHO, compiling contract should not block the further development. Any informative document about solc should work out of box.

**Comment by ender503** [comment]
The rest of the undone EVM API are: 
1. contract deployment API
  - Need to compile the received contract first, then we could deploy to the EVM nodes.
2. interact with contract API
  - Depend on 1. 

After discussing with @mushroom0117 yesterday, we are planned to use the `solc-js` to compile the contract on the server-side.

And using the [loadRemoteVersion()](https://github.com/ethereum/solc-js#using-the-latest-development-snapshot) to support the legacy solidity version (e.g. 0.4.x).

**Comment by mushroom0117** [comment]
Based on [loadRemoteVersion()](https://github.com/ethereum/solc-js#using-the-latest-development-snapshot), the smart contract below solidity v0.5.8 (latest) can be supported, the user only needs to  specifying the [version numbers](https://ethereum.github.io/solc-bin/bin/list.js). The uploading contract will be compiled on the server-side.
