### ISSUE TITLE
Base: IRI attachToTangle API parallelism investigation

### ISSUE THREAD

**Issue by marktwtn** [DLTcollab/general#149]
An incoming feature of dcurl is allowing the PoW calculation to be distributed to the remote FPGA boards through the network.

However, the current `attachToTangleStatement()` API has the keyword `synchronized`.
It means that it only allows one transaction bundle to be handled by the `dcurl` at the same time.
That is, `dcurl` only handles one PoW calculation at the same time.

The issue focuses on the discussion of removing the `synchronized` keyword would have side-effect or not.
If no side-effect is found, then the remote FPGA boards can work well with the multiple transactions incoming.

**Comment by jserv** [comment]
The investigation should be quite typical and well addressed.
Related information: https://www.confluent.io/blog/transactions-apache-kafka/

**Comment by marktwtn** [comment]
After reading the source code of [API.java](https://github.com/DLTcollab/iri/blob/dev-rebase/src/main/java/com/iota/iri/service/API.java#L1437) ,it seems like the `synchronized` keyword of `attachToTangleStatement()` can be removed safely.
I do not recognize any data race and it simply does the **PoW** of the bundle one by one, then return the final transaction result.

I guess the main reason of using the `synchronized` keyword is it requires trunk and branch transaction.
However, to get the trunk and branch transaction, it needs the `getTransactionsToApprove()` function, which is `synchronized` in the **IF** repository.

A brief conclusion:
1. The `synchronized` keyword can be removed since our `getTransactionToApprove()` of DLTCollab is not synchronized at all.
2. The source code of function `attachToTangleStatement()` should be modified since it contains logging the consumed time of every 100 **PoW**. The calculation method should be redesigned if `attachToTangleStatement()` is not `synchronized`.

**Comment by jserv** [comment]
Is it vital to rewrite the logic behind `attachToTangleStatement`? Is there any performance metric indicating how the time takes in typical configurations?

**Comment by marktwtn** [comment]
We do not have to rewrite the logic.
We just need to modify the logging part of the consumed time of every 100 **PoW**, which is just an extra and small calculation code in `attachToTangleStatement()`.

Currently, I do not know any performance metric.
I might investigate for it.

**Comment by marktwtn** [comment]
The parallel `attachToTangleStatement()` modification https://github.com/DLTcollab/iri/pull/4 is merged.

However, if the `dcurl` remote interface is not introduced, the parallel `attachToTangleStatment()` may make the hardware have a great loading because of the multiple PoW at the same time.
