### ISSUE TITLE
Base: Survey wallets using TEE

### ISSUE THREAD

**Issue by ajblane** [DLTcollab/general#151]
Here are short summaries from papers and slides 

2017, [Improving the Security and Efficiency of Blockchain-based Cryptocurrencies](https://pdfs.semanticscholar.org/442a/d0d4c4c58ba4803f3206a94b81d84836aa25.pdf)
* Bitcoin payment are made form/to cryptographic key
* TEE-protected key
* TEE-provided attestation

2017, [Teechan: Payment Channels Using Trusted Execution Environments](https://www.cs.cornell.edu/people/egs/papers/teechan.pdf)
* TEE use attestation to create secure channel between them
 
[VERSION 0.8.0 AnyLedger: Embedded wallet for decentralized IoT](http://www.anyledger.io/whitepaperAnyLedger.pdf)
* For AnyLedger embedded wallet, TrustZone is used for private key generation, private key storage and transaction signing.

2016, [LAS16-306: Exploring the Open Trusted Protocol](https://www.slideshare.net/linaroorg/las16306-exploring-the-open-trusted-protocol?from_action=save)
2018, [TEE Management Framework: Open Trust Protocol (OTrP) Profile](https://globalplatform.org/wp-content/uploads/2018/11/GPD_TMF_OTrP_Profile_v0.0.0.21_PublicReview.pdf)
[dthaler/OTrP - C Implementation of draft-ietf-teep-opentrustprotocol](https://github.com/dthaler/OTrP)
* Open and Secure framework for Over-The-Air management of Secure Keys and Trusted Application (TA)
* Based on the standard PKI (Public Key Infrastructure)
* Attestation between TAM(Trusted Application Management) and TEE-device with Key pair and Certificate for remote integrity check
* Cryptography based authentication with certified asymmetric device keys

2018, [PrivacyGuard : Enforcing Private Data Usage with Blockchain and Attested Execution](https://cybersecurity.seas.wustl.edu/ning/paper/PrivacyGuardDPM18.pdf)
2019, [Enforcing Private Data Usage Control with Blockchain and Attested Off-chain Contract Execution](https://arxiv.org/pdf/1904.07275.pdf)
* PrivacyGuard, a private data utilization framework
* **Assume collected information via IOT devices is trusted**
* iDataAgent program runs in a TEE and acts as **a broker** for user data
* iDataAgent manages the keys for the data owner and 
* iDataAgent encrypts/ decrypts the data for that user
* Sensitive data will be encrypted by the iDataAgent before pushed to the cloud for storage
* iDataAgent is also responsible to remotely attestation in TEE before passing the data decryption key to it
* Encrypted storage in cloud

**Comment by wusyong** [comment]
@ajblane Is it still under survey? Or it's good to close?
