### ISSUE TITLE
Construct EVM-Lite API monorepo

### ISSUE THREAD

**Issue by mushroom0117** [DLTcollab/general#152]
To make the developer easier to use the EVM-Lite, create an EVM-Lite API monorepo.

**Expected Include**

- [ ]  EVM-Lite Docker Environment Setup Script ( Experience )
- [ ]  EVM-Lite Golang Deployment Script
- [ ]  EVM-Lite API Service
- [ ]  EVM-Lite API Reference ( Typescript )

**Comment by jserv** [comment]
@mushroom0117, any update?

**Comment by mushroom0117** [comment]
@jserv [Library](https://github.com/mushroom0117/EVM-Engine-Lib) has been completed and deployed to [npmjs](https://www.npmjs.com/package/evm-engine-lib). 
This will make users easier to start a transaction or deploy the contracts via evm-lite.

**Comment by jserv** [comment]
Let's close this issue first and split into several functional subtasks.
