### ISSUE TITLE
TangleID: Evaluate the Universal Resolver

### ISSUE THREAD

**Issue by ender503** [DLTcollab/general#153]
Decentralized Identity Foundation releases a [universal resolver](https://github.com/decentralized-identity/universal-resolver) for resolving DID from different DID methods, we'll need to evaluate how to integrate it with TangleID.

Online universal resolver: https://uniresolver.io/

**Comment by ender503** [comment]
I set up an universal resolver on the node0:
http://node0.puyuma.org:8080/1.0/identifiers/did%3Asov%3AWRfXPg8dantKVubE3HX8pwTh

**Comment by ender503** [comment]
For the real world use cases, the client may receive the credential that signed by an entity which was registered to another DLT, using the universal resolver will give us the ability to verify these credentials.

**Comment by jserv** [comment]
> I set up an universal resolver on the node0:

Should be "a universal"

**Comment by ender503** [comment]
Oh ... there are some exceptions. 👍 
[When to Say "a" or "an" | Pronunciation | EnglishClub](https://www.englishclub.com/pronunciation/a-an.htm)

**Comment by ender503** [comment]
Add another issue to integrate the document loader with the universal resolver.

https://github.com/TangleID/TangleID/issues/142
