### ISSUE TITLE
Base: Register all available IOTA full node to Trintiy

### ISSUE THREAD

**Issue by jserv** [DLTcollab/general#156]
[IOTA Node List](https://iota-nodes.net) maintain informative listing for specific IOTA nodes. It is important for people to discover full nodes. This task is to register the nodes maintained at NCKU to the listing.

**Comment by wusyong** [comment]
Change target to Trinity since it will has most views from majority.

**Comment by mushroom0117** [comment]
`devorg` has successfully added to Trinity node list.
