### ISSUE TITLE
Base: Evaluate performance increment of parallel attachToTangle API

### ISSUE THREAD

**Issue by marktwtn** [DLTcollab/general#162]
After the `dcurl` introduces remote interface, `IRI` can benefit from it with parallelizing **attachToTangle** API.
However, the performance increment is still unknown.
And the parallelism should be measured.

Goal:
- [x] Stable `dcurl` remote interface with multiple FPGA boards.
- [x] Source code modification of parallel **attachToTangle** API [#4](https://github.com/DLTcollab/iri/pull/4).
- [x] Setup two `IRI` for comparison with one has parallel **attachToTangle** API and the other does not.
- [x] Send IOTA API http requests to `IRI` with IOTA API library.
- [x] Compare the logging information of the consumed time
- [x] Use tool like `jvm monitor` or `jstack` to acquire the thread information.
- [x] Generate the final performance increment report.

**Comment by marktwtn** [comment]
I wrote a python script to send **attachToTangle** http requests.
Steps:
- Obtain the tips from the previous **getTips** http request.
- Get a transaction bundle with 2 zero value transaction.
- Create N threads for sending **attachToTangle** http requests:
    - Substitute the trunk and branch transaction hash of the zero value transaction with randomly selected tips.

There are some code need to be determined and modified, like the thread number and so on.
But the main function is achieved.

**Comment by marktwtn** [comment]
A simple performance measurement:

Sending 100 **attachToTangle** http requests to IRI with sleeping 2 second every 50 requests.
The data is the duration from the response of the http requests.
![graph](https://user-images.githubusercontent.com/6748200/61607136-e4be1f80-ac7f-11e9-8830-692af8e3bd01.png)

The **IRI-RELEASE** is the worst since its **attachToTangleStatement()** function is synchronized.
As the number of the remote **dcurl** increase, the performance become better.

**Comment by marktwtn** [comment]
**jstack** - Prints Java thread stack traces for a Java process

We can get the instant thread information with **jstack**:
```
"XNIO-1 task-347" #875 prio=5 os_prio=0 tid=0x00007fb708018800 nid=0xe3b2 runnable [0x00007fb1df631000]
   java.lang.Thread.State: RUNNABLE
        at com.iota.iri.crypto.PearlDiver.exlibSearch(Native Method)
        at com.iota.iri.crypto.PearlDiver.search(PearlDiver.java:99)
        at com.iota.iri.service.API.attachToTangleStatement(API.java:1292)
        at com.iota.iri.service.API.lambda$attachToTangle$13(API.java:1550)
        at com.iota.iri.service.API$$Lambda$18/1721246982.apply(Unknown Source)
        at com.iota.iri.service.API.process(API.java:280)
        at com.iota.iri.service.API$$Lambda$79/107994825.processFunction(Unknown Source)
......
```

The full print out messages show that there are a lot of threads running the `attachToTangle` function.
However, not all of them are really using the FPGA remote worker to calculate the PoW.
Since the FPGA board resource is limited, the other threads are waiting for the source release.

Hence the parallelism of **attachToTangle** API can not be measured with **jstack**.
And the maximum parallelism is just the same as the max FPGA board resource.
Maybe we can use **RabbitMQ** management to observe the parallelism in a sequential time.

**Comment by jserv** [comment]
> However, not all of them are really using the FPGA remote worker to calculate the PoW.
> Since the FPGA board resource is limited, the other threads are waiting for the source release.

I am curious about the quantitative approach to analyze the workers powered by FPGA accelerator. Would you audit the transactions along with them?

**Comment by marktwtn** [comment]
There is one thing I need to mention.

When the `IRI` executes **attachToTangle** in parallel, they would compete for the resource of remote `dcurl`.
For example, **attachToTangle** handles a transaction bundle consisting of multiple transactions.
When the first transaction has finished its PoW calculation with remote `dcurl`, the second transaction might need to wait for the remote `dcurl` since it might be hold by the transactions of the other transaction bundles.
Hence an execution of **attachToTangle** can be longer than we expected if the resource is not enough or there are too many requests coming at the same time.

**Comment by jserv** [comment]
Can we introduce producer-consumer concurrency patterns? Otherwise, we waste computing resources for waiting the racing.

Reference: https://dzone.com/articles/concurrency-pattern-producer

**Comment by marktwtn** [comment]
> A simple performance measurement:
> 
> Sending 100 **attachToTangle** http requests to IRI with sleeping 2 second every 50 requests.
> The data is the duration from the response of the http requests.
> ![graph](https://user-images.githubusercontent.com/6748200/61607136-e4be1f80-ac7f-11e9-8830-692af8e3bd01.png)

In the chart, we can see that the response time of using local `dcurl` is slightly faster than remote `dcurl` on a `de10-nano` board.
It is reasonable if we check the hash rate value.

| Hardware | Hash rate(kH/sec) |
| :---: | :---: |
| node1 with 8 threads | 17344 |
| de10-nano board | 33734 |
| node1 with 64 threads | 51544 |

The line of local `dcurl` uses 64 threads. Hence it behaves better when comparing to a single `de10-nano` board.

**Comment by jserv** [comment]
IOTA fullnode might be hosted within virtualized environments where 64 cpu is not a common configuration for each instance. Instead, FPGA boards consume less power and might be a solution for scalability while total cost of ownership (TCO) is considered.

**Comment by jserv** [comment]
To evaluate the scalability of remote interface, more FPGA configurations shall be enabled for comparison.

**Comment by marktwtn** [comment]
I extract the time of **RabbitMQ + Internet** in **attachToTangle** execution and compare with the different number of the remote workers.

Sending 100 **attachToTangle** API requests and doing 200 PoW (1 request contains 2 transactions):
![remote](https://user-images.githubusercontent.com/6748200/64399165-0d687000-d09a-11e9-97e6-40036dc2e567.png)

Since the internet remains the same, we can see from the chart that as the remote worker increases, the time of **RabbitMQ** decreases.
The decreasing behaviour is due to the faster consumption of queued messages by more remote workers.

**Comment by marktwtn** [comment]
The new experiment result with sending 200 **attachToTangle** requests.

![graph](https://user-images.githubusercontent.com/6748200/65930857-e8b5ad00-e439-11e9-9f6a-8e70d4ea8e0d.png)

There is a new data of having 4 FPGA boards.

The result is just like the previous chart, which shows that the PoW calculation with around 64 CPU threads would slightly faster than a single `de10-nano` FPGA board.
However, if we have **at least 2 `de10-nano` FPGA boards**, the response time would be shorter
And it would behave better as the number of boards increases.

**Comment by marktwtn** [comment]
The time of **RabbitMQ + Internet** in **attachToTangle** execution also decreases as the number of remote worker increases.

![remote](https://user-images.githubusercontent.com/6748200/65980819-77621280-e4aa-11e9-8d13-f74a809887bd.png)

**Comment by jserv** [comment]
Can you try the configurations pointed by [Linux low-latency](https://summonersrift.github.io/blog/linux-low-latency/) for DE10 Nano?

**Comment by jserv** [comment]
Another reference: https://kkc.github.io/2017/12/18/Network-Performance-Tuning/

**Comment by marktwtn** [comment]
The new experiment result with sending 200 attachToTangle requests with each containing 2 transactions.

![bundle](https://user-images.githubusercontent.com/6748200/68555885-cec0ae80-046a-11ea-8774-9ac4cc146f5e.png)

There are some data missing due to the log lost.
I'll fix it and generate the corresponding statistic data.

**Comment by jserv** [comment]
Cc. @yillkid, please prepare and revise text descriptions as well

**Comment by marktwtn** [comment]
The experiment result with sending 200 attachToTangle requests with each containing 2 transactions.

- The IRI and RabbitMQ broker are on the same machine
- The RabbitMQ broker and remote workers are on the same local network

![bundle](https://user-images.githubusercontent.com/6748200/68823502-e7310300-06ce-11ea-8854-4ba713ebb11c.png)

Except the requests at the beginning, the growth of the required time is linear.
Hence I pick the median of the data as the comparison result.

| Architecture | Second (Median ) | Acceleration ratio (Compare with local) |
| - | - | - |
| Local | 40.808 | 100% |
| Remote worker * 1 | 42.604 | 95.78% |
| Remote worker * 2 | 20.395 | 200.09% |
| Remote worker * 4 | 10.726 | 380.46% |
| Remote worker * 8 | 4.458 | 915.39% |

---

Since the **attachToTangle** API is parallel, the consumed time of each request can not present the overall handling time.
I use Linux command `time` to measure the overall time from my desktop to IRI, and back to my desktop.

| Architecture | Second | Acceleration ratio (Compare with local) |
|-|-|-|
| Local | 60.153 | 100% |
| Remote worker * 1 | 56.778 | 105.94% |
| Remote worker * 2 | 30.652 | 196.24% |
| Remote worker * 4 | 16.902 | 355.89% |
| Remote worker * 8 | 9.353 | 643.14% |

**Comment by jserv** [comment]
Since IRI has been deprecated, let's work on HORNET as on-going tasks.
