### ISSUE TITLE
Ansible playbook for restoring database files

### ISSUE THREAD

**Issue by yillkid** [DLTcollab/general#166]
An Ansible playbook for restoring database files when the `latestSolidSubtangleMilestoneIndex` be stuck or reset.

#### Architecture and WorkFlow:
![Arc](https://user-images.githubusercontent.com/185872/59508695-5e285c80-8ee1-11e9-995f-ed658e5e01b5.png)

1. stop iri-mainnet service
2-1 full-node: restore local snapshot files
2-2 permanode: restore mainnet database files
3. start iri-mainnet service

- TODO:
  - [x] Add a fake systemd service and DB file
  - [x] Testing and implement the detail of workflow point 1 ~ 3
  - [x] Switch to IRI service
  - [ ] Update IT documents

- Reference
  - [systemd - Manage services](https://docs.ansible.com/ansible/2.5/modules/systemd_module.html)

**Comment by yillkid** [comment]
Deploy a `hello-world.service` on node0 : 

$ systemctl status hello-world.service
```
● hello-world.service - Hello World Service
   Loaded: loaded (/etc/systemd/system/hello-world.service; static; vendor preset: enabled)
   Active: active (running) since Mon 2019-06-24 12:43:25 CST; 1min 38s ago
 Main PID: 15636 (hello-world.sh)
    Tasks: 2 (limit: 4915)
   CGroup: /system.slice/hello-world.service
           ├─15636 /bin/bash /home/ubuntu/fake_systemd/hello-world.sh
           └─15855 sleep 30
```

**Comment by yillkid** [comment]
Change IRI database backup scheduler from `crontab` to `systemd` timer, the advantage as below:
- Automatic log rotation
- Easy to debug: systemctl lets you view logs, exit codes, and timer history
- Easy to stop by Ansible-playbook

To add one backup systemd service and correspond timer:
/etc/systemd/system/iri-mainnet-backup.service:
```
[Unit]
Description=IRI mainnet backup

[Service]
Type=simple
SyslogLevel=debug
User=ubuntu
ExecStart= /home/ubuntu/backup_iri_mainnetdb.sh
WorkingDirectory=/home/ubuntu/
```
iri-mainnet-backup.timer:
```
[Unit]
Description=IRI-mainnet timer tasks

[Timer]
OnCalendar=*-*-* 01:00:00
Persistent=true
Unit=iri-mainnet-backup.service

[Install]
WantedBy=multi-user.target
```

TODO:
- [ ] Add `iri-mainnet-backup.timer` stop command in Ansible-playbook

**Comment by ender503** [comment]
### Note
 - This playbook only takes care of restoring the IRI database from snapshot files.
 - We need another playbook to install the IRI database backup timer.
 - The IRI database backup timer shall run by another account which also runs the IRI service.
 - Playbook has lots of useful modules, the shell scripts(e.g. backup_iri_db, recovery_iri_db) may migrate to the playbook.

**Comment by wusyong** [comment]
@yillkid Would you like to integrate into iri-playbook? I think what @ender503 said can be done there.

**Comment by ender503** [comment]
@yillkid The iri-playbook repository already moved to the [DLTcollab/iri-playbook](https://github.com/DLTcollab/iri-playbook), thanks @wusyong . 👍
