### ISSUE TITLE
Infra: Duplicate NCKU based services to NCTU

### ISSUE THREAD

**Issue by ender503** [DLTcollab/general#179]
To move servers from NCKU to NCTU, I will write a proposal and discuss with @yillkid  and @wusyong to check what we need.

**Comment by jserv** [comment]
Clarification: not *moving*. Instead, the task is to duplicate existing and refine existing infrastructure.

**Comment by ender503** [comment]
@jserv So NCTU will provide the servers and we need to set up the services to their servers?

**Comment by jserv** [comment]
There are expectedly new servers hosted in NCTU. We shall concentrate on service duplications and migrations.

**Comment by ender503** [comment]
Sounds great 👍

**Comment by ender503** [comment]
After discussing with @yillkid and @wusyong, here are our requirements and questions about NCTU.
https://hackmd.io/D2u2MiL2STy736BASayNpA

It needs to be check with the NCTU.

**Comment by yillkid** [comment]
> Yillkid Huang <yillkid@biilabs.io> 
寄給 婁傑、 Ching-Chun、 John、 Yichen、 cyhuang 
> - - -
> Hi Jeremy
>
> 您好！我是 NCKU 這邊的聯絡窗口。
>
> 我們預計遷移到交大的主機，基本資訊如下：
>
>Hardware:
> - [specification](https://gist.github.com/yillkid/cec126a888c9fa1d2fb48ccb60ebf1da)
>
> - Network traffic: around 1.5GB per day (IN: 860MB,OUT: 700MB)[1]
>  - [1] https://iota.stackexchange.com/questions/665/estimation-of-network-traffic-for-a-full-node
>
> 想請教您關於交大的幾個 IT 相關規定：
> 1. 遷移的主機型態為一般的 PC (非機架伺服器)，請問是否能夠佈署在機櫃上？
> 2. 請問交大是否需要事先申請 public IP？
> 3. 請問交大對佈署的伺服器，是否做通訊埠控管？
> 4. 請問計中能夠容許的網路流量。
> 
> 謝謝您，
> -- 俊毓

**Comment by yillkid** [comment]
> We will move node10 to NCTU firstly.
> 
> > Yillkid Huang [yillkid@biilabs.io](mailto:yillkid@biilabs.io)
> > 寄給 婁傑、 Ching-Chun、 John、 Yichen、 cyhuang
> > 
> > Hi Jeremy
> > 您好！我是 NCKU 這邊的聯絡窗口。
> > 我們預計遷移到交大的主機，基本資訊如下：
> > Hardware:
> > 
> > * [specification](https://gist.github.com/yillkid/cec126a888c9fa1d2fb48ccb60ebf1da)
> > * Network traffic: around 1.5GB per day (IN: 860MB,OUT: 700MB)[1]
> > * [1] https://iota.stackexchange.com/questions/665/estimation-of-network-traffic-for-a-full-node
> > 
> > 想請教您關於交大的幾個 IT 相關規定：
> > 
> > 1. 遷移的主機型態為一般的 PC (非機架伺服器)，請問是否能夠佈署在機櫃上？
> > 2. 請問交大是否需要事先申請 public IP？
> > 3. 請問交大對佈署的伺服器，是否做通訊埠控管？
> > 4. 請問計中能夠容許的網路流量。
> > 
> > 謝謝您，
> > -- 俊毓

您好,

我是黃老師這邊的聯絡窗口!

1.我們的機櫃，不太適合放置一般的主機，不過主機可以放在實驗室的桌子上，或是在伺服器機房都可以，位置可以再討論，但機櫃比較適合機架型的。
2.如果只是需要1個public IP, 我們LAB 本來就有多餘的public IP可以使用，但如果需要蠻多的，就會需要在向計中申請。
3.電資大樓這邊並不會特別對我們實驗室部屬的伺服器做管理
4.如果一天的流量是總共1.5GB, 我想我們的網路已經足夠，實驗室使用的每個網路port都是從同一台電資大樓的router進行分配的，如果有網路方面的需求，我們可以在詢問計中。

我看你在第四點附的連結的計算它們需要62.94 Mbit/sec，如果要到這麼快，我們會需要去問紀中能不能開放高速的網路給我們使用，但如果是一天1.5GB,可以使用原本的就好，謝謝!

Best,
Jeremy

**Comment by yillkid** [comment]
> > We will move node10 to NCTU firstly.
> > > Yillkid Huang [yillkid@biilabs.io](mailto:yillkid@biilabs.io)
> > > 寄給 婁傑、 Ching-Chun、 John、 Yichen、 cyhuang
> > > Hi Jeremy
> > > 您好！我是 NCKU 這邊的聯絡窗口。
> > > 我們預計遷移到交大的主機，基本資訊如下：
> > > Hardware:
> > > 
> > > * [specification](https://gist.github.com/yillkid/cec126a888c9fa1d2fb48ccb60ebf1da)
> > > * Network traffic: around 1.5GB per day (IN: 860MB,OUT: 700MB)[1]
> > > * [1] https://iota.stackexchange.com/questions/665/estimation-of-network-traffic-for-a-full-node
> > > 
> > > 想請教您關於交大的幾個 IT 相關規定：
> > > 
> > > 1. 遷移的主機型態為一般的 PC (非機架伺服器)，請問是否能夠佈署在機櫃上？
> > > 2. 請問交大是否需要事先申請 public IP？
> > > 3. 請問交大對佈署的伺服器，是否做通訊埠控管？
> > > 4. 請問計中能夠容許的網路流量。
> > > 
> > > 謝謝您，
> > > -- 俊毓
> 
> 您好,
> 
> 我是黃老師這邊的聯絡窗口!
> 
> 1.我們的機櫃，不太適合放置一般的主機，不過主機可以放在實驗室的桌子上，或是在伺服器機房都可以，位置可以再討論，但機櫃比較適合機架型的。
> 2.如果只是需要1個public IP, 我們LAB 本來就有多餘的public IP可以使用，但如果需要蠻多的，就會需要在向計中申請。
> 3.電資大樓這邊並不會特別對我們實驗室部屬的伺服器做管理
> 4.如果一天的流量是總共1.5GB, 我想我們的網路已經足夠，實驗室使用的每個網路port都是從同一台電資大樓的router進行分配的，如果有網路方面的需求，我們可以在詢問計中。
> 
> 我看你在第四點附的連結的計算它們需要62.94 Mbit/sec，如果要到這麼快，我們會需要去問紀中能不能開放高速的網路給我們使用，但如果是一天1.5GB,可以使用原本的就好，謝謝!
> 
> Best,
> Jeremy

Hi Jeremy

看起來沒有什麼太大的問題需要解決，
我看是不是挑選一天我們把主機先搬過去，完成以下工作：
1. 主機部屬
2. Public IP 設置
3. 確保 sshd 能夠透過遠端登入

目前需要討論的項目：
1. 設置地點：暫定伺服器機房
2. NCKU 這邊前往設置的日期：請交大這邊討論 (我們這邊週一 ~ 日皆可)

謝謝您，
-- 俊毓

**Comment by yillkid** [comment]
> > > We will move node10 to NCTU firstly.
> > > > Yillkid Huang [yillkid@biilabs.io](mailto:yillkid@biilabs.io)
> > > > 寄給 婁傑、 Ching-Chun、 John、 Yichen、 cyhuang
> > > > Hi Jeremy
> > > > 您好！我是 NCKU 這邊的聯絡窗口。
> > > > 我們預計遷移到交大的主機，基本資訊如下：
> > > > Hardware:
> > > > 
> > > > * [specification](https://gist.github.com/yillkid/cec126a888c9fa1d2fb48ccb60ebf1da)
> > > > * Network traffic: around 1.5GB per day (IN: 860MB,OUT: 700MB)[1]
> > > > * [1] https://iota.stackexchange.com/questions/665/estimation-of-network-traffic-for-a-full-node
> > > > 
> > > > 想請教您關於交大的幾個 IT 相關規定：
> > > > 
> > > > 1. 遷移的主機型態為一般的 PC (非機架伺服器)，請問是否能夠佈署在機櫃上？
> > > > 2. 請問交大是否需要事先申請 public IP？
> > > > 3. 請問交大對佈署的伺服器，是否做通訊埠控管？
> > > > 4. 請問計中能夠容許的網路流量。
> > > > 
> > > > 謝謝您，
> > > > -- 俊毓
> > 
> > 
> > 您好,
> > 我是黃老師這邊的聯絡窗口!
> > 1.我們的機櫃，不太適合放置一般的主機，不過主機可以放在實驗室的桌子上，或是在伺服器機房都可以，位置可以再討論，但機櫃比較適合機架型的。
> > 2.如果只是需要1個public IP, 我們LAB 本來就有多餘的public IP可以使用，但如果需要蠻多的，就會需要在向計中申請。
> > 3.電資大樓這邊並不會特別對我們實驗室部屬的伺服器做管理
> > 4.如果一天的流量是總共1.5GB, 我想我們的網路已經足夠，實驗室使用的每個網路port都是從同一台電資大樓的router進行分配的，如果有網路方面的需求，我們可以在詢問計中。
> > 我看你在第四點附的連結的計算它們需要62.94 Mbit/sec，如果要到這麼快，我們會需要去問紀中能不能開放高速的網路給我們使用，但如果是一天1.5GB,可以使用原本的就好，謝謝!
> > Best,
> > Jeremy
> 
> Hi Jeremy
> 
> 看起來沒有什麼太大的問題需要解決，
> 我看是不是挑選一天我們把主機先搬過去，完成以下工作：
> 
> 1. 主機部屬
> 2. Public IP 設置
> 3. 確保 sshd 能夠透過遠端登入
> 
> 目前需要討論的項目：
> 
> 1. 設置地點：暫定伺服器機房
> 2. NCKU 這邊前往設置的日期：請交大這邊討論 (我們這邊週一 ~ 日皆可)
> 
> 謝謝您，
> -- 俊毓

您好,

我時間是星期一到星期五都OK。

地點: 交通大學電子與資訊研究中心 R213

謝謝您,
婁傑

--- 

@jserv , @ender503 你們還有沒有要補充的，否則我即將：
1. 跟 NCTU 網管要一張佈署環境的照片，以確保 node10 能夠順利置入
2. 根據環境照片評估日後 switch 與 FPGA 開發板等等是否還有增加餘地
3. 與 NCTU 網管約時間，準備出發

我預計會在週一～五選擇一天開車北上至新竹。

**Comment by ender503** [comment]
@yillkid why this issue is moved to `In Progress`? any update?

**Comment by yillkid** [comment]
Done.

**Comment by yillkid** [comment]
I suggest change this issue to EPIC, including issues as below:
- Computer facilities on NCTU
  - Need a larger space or choice a new one.
  - To buy new server cabinet and switch.
- Virtual Machine
  - Environment setup
  - Wait for NCTU expanded memory (from 10 GB to 64 GB) for VM (node8).
- IT Policy
  - Documented
- [NCTU Requirements & Questions](https://hackmd.io/D2u2MiL2STy736BASayNpA)
  - @ender503 , we should change the permission for the about documentation.

**Comment by ender503** [comment]
I think this issue could be closed because we already move the node10 to NCTU, and no need to duplicate the service (They are already on the Node10).

**Comment by ender503** [comment]
You could open the issues to track each following task, and you should explain more detail, otherwise I could not understand what are you planning to do.
> I suggest change this issue to EPIC, including issues as below:

> * `node10` server information and all services checking
What is your expected output? update node10 server information? or set up monitoring service for what?

> * IT Policy
>   * Documented
What are you planning to do? Update the document or something else?

> * [NCTU Requirements & Questions](https://hackmd.io/D2u2MiL2STy736BASayNpA)
>   * @ender503 , we should change the permission for the about documentation.
Do you mean that change this note to private?

**Comment by yillkid** [comment]
> You could open the issues to track each tasks, and you should explain more detail, otherwise I could not understand what are you planning to do.
> 
> > I suggest change this issue to EPIC, including issues as below:
> 
> > * `node10` server information and all services checking
> 
> What is the expected output? update node10 server information? or set up monitoring service for what?
> 
> > * IT Policy
> >   
> >   * Documented
> 
> What are you planning to do? Update the document or something else?
> 
> > * [NCTU Requirements & Questions](https://hackmd.io/D2u2MiL2STy736BASayNpA)
> >   
> >   * @ender503 , we should change the permission for the about documentation.
> 
> Do you mean that change this note to private?

I think to close this issue is OK.
I will open a new EPIC and describe the issue about the follow-up work more detail.
