### ISSUE TITLE
TangleID: Use ISS for signature?

### ISSUE THREAD

**Issue by yillkid** [DLTcollab/general#18]
In gitlab by @root on Dec 12, 2017, 00:49

*Created by: louielu*

Milestone using [ISS](https://github.com/iotaledger/iri/blob/dev/src/main/java/com/iota/iri/hash/ISS.java) to verify milestone signature with [public key](https://github.com/iotaledger/iri/blob/dev/src/main/java/com/iota/iri/Snapshot.java#L23).

Not sure if TangleID can use this create it's public/private key, and then is will no need to use RSA as external keypair.

Python version of ISS is at [here](https://github.com/mlouielu/iota-python/blob/milestone/iotapy/snapshot.py)

**Comment by yillkid** [comment]
In gitlab by @root on Dec 28, 2017, 11:50

*Created by: HexRabbit*

Is coordinator using one-time signature method or private public key pair?

**Comment by yillkid** [comment]
In gitlab by @root on Jan 10, 2018, 17:00

assigned to @louielu

**Comment by yillkid** [comment]
In gitlab by @jserv on Mar 16, 2018, 23:26

changed title from **{-Use ISS to signature tangle ID-}?** to **{+TangleID: Use ISS for signature+}?**

**Comment by yillkid** [comment]
In gitlab by @jserv on Mar 16, 2018, 23:27

@louielu, how do you think of the feasibility?

**Comment by jserv** [comment]
@HexRabbit, @ender503: Evaluate the feasibility. If it is not worthy, let's close this.

**Comment by ender503** [comment]
Defer to @HexRabbit .

**Comment by HexRabbit** [comment]
There's a problem, I've said wrong about that use case.
ISS only provide a **one-time** connection between 

**address**(by hash(hash(private key & tx data))) and **signature**(by hash((private key & tx data)), 

in this case we cannot know **who owned** this address, the only thing we know is that this tx address is used by its owner, but what we want is a connection between a authenticated, **not expirable public key (a owner)** and a **signature**, thus ISS is not suitable for our application.
