### ISSUE TITLE
Buy DE10-Nano Kit (8 pieces)

### ISSUE THREAD

**Issue by yillkid** [DLTcollab/general#187]
* [x] Prepare [DE10-Nano Kit](https://www.terasic.com.tw/cgi-bin/page/archive.pl?Language=Taiwan&CategoryNo=173&No=1047)
- Quantity: 8 pieces

**Comment by yillkid** [comment]
@jserv , we will have a total of 11 FPGA board after buying 8 new ones. Therefore we need to buy a new router to manage these target boards, the requirement as below:

1. 16 ports at least: 12 FPGA boards and 4 servers
2. VLAN: To plan the virtual local area network for loading balancing
3. DHCP: Management IP and VLAN for target boards and servers
4. Rack-mounted: For hardware deploy policy

My suggestion is [D-Link DGS-1210-28](https://24h.pchome.com.tw/prod/DRAF6A-A66157845?fq=/S/DSBA1P).

I will order router and FPGA boards together if you agree that.

**Comment by jserv** [comment]
Be aware of the fact that one of existing servers in NCKU will be taken to NCTU after we decide the configurations for FPGA boards. So, the old switch might be still functioned as well. Go ahead to proceed order.

**Comment by yillkid** [comment]
![0](https://user-images.githubusercontent.com/185872/62413941-04722200-b648-11e9-8bf3-98801e41a653.png)

[DE10-Nano] DE10-Nano Board (教育版) x 8 pieces
total: $32,360

C.c @jserv

**Comment by yillkid** [comment]
DE10-Nano Kit ordered already.

**Comment by yillkid** [comment]
The de10 nano (8 pieces) have arrival to NCKU on 2019-08-06, will set up with full-node (node1, node10) with @marktwtn.
