### ISSUE TITLE
Infra: Statically assign MAC addresses of FPGA boards

### ISSUE THREAD

**Issue by ender503** [DLTcollab/general#189]
Since the FPGA boards change its MAC address every time on the startup, we could not allocate the IP address depending on its MAC address.

To make FPGA boards MAC address static, use the `macchanger`.

Reference: 
 - [How to change the MAC address of an Ethernet interface](https://blog.sleeplessbeastie.eu/2013/01/11/how-to-change-the-mac-address-of-an-ethernet-interface/)

**Comment by yillkid** [comment]
@marktwtn , since you could set the fixed MAC address value at system startup, could you provide the MAC address of 3 piece FPGA board? :)

**Comment by marktwtn** [comment]
> @marktwtn , since you could set the fixed MAC address value at system startup, could you provide the MAC address of 3 piece FPGA board? :)

After the discussion with @ender503 , I decide to give it a try by modifying the file `/etc/network/interfaces`.
If it does not work at all, I will use the original method of modifying `/etc/rc.local` and give you the MAC addresses.

**Comment by marktwtn** [comment]
I add the line `hwaddress ether xx:xx:xx:xx:xx:xx` after the 
```
auto eth0
iface the0 inet dhcp
```
in **/etc/network/interfaces**.
It turns out we still need to enter the command `$ dhclient -v eth0` to activate the `eth0`.
Otherwise, we would have `lo` only.

The current workaround is adding the `dhclient` command in `/etc/rc.local`.
@yillkid do you have any suggestion?

**Comment by ender503** [comment]
Seems like this is the only way to run the `dhclient` on startup for now.

See also: [Run dhclient on Startup in Ubuntu 18.04](https://gist.github.com/mohamadaliakbari/1cb9400984094541581fff07143e1c9d)

**Comment by yillkid** [comment]
> I add the line `hwaddress ether xx:xx:xx:xx:xx:xx` after the
> 
> ```
> auto eth0
> iface the0 inet dhcp
> ```
> 
> in **/etc/network/interfaces**.
> It turns out we still need to enter the command `$ dhclient -v eth0` to activate the `eth0`.
> Otherwise, we would have `lo` only.
> 
> The current workaround is adding the `dhclient` command in `/etc/rc.local`.
> @yillkid do you have any suggestion?

Seems we have a setting problem on interfaces configuration, but we can open a new issue to trace it.
We still can use `rc.local` to fixed the MAC address then I will MAP IP/MAC mapping in DHCP server.

**Comment by ender503** [comment]
> I add the line `hwaddress ether xx:xx:xx:xx:xx:xx` after the
> 
> ```
> auto eth0
> iface the0 inet dhcp
> ```
> 
> in **/etc/network/interfaces**.
> It turns out we still need to enter the command `$ dhclient -v eth0` to activate the `eth0`.
> Otherwise, we would have `lo` only.
> 
> The current workaround is adding the `dhclient` command in `/etc/rc.local`.
> @yillkid do you have any suggestion?

The settings are applied on all the FPGA boards, and MAC addresses are static.
Let's close this issue.

**Comment by marktwtn** [comment]
It turns out that we do not need the `dhclient` command in `/etc/rc.local` anymore.
The `dhclient` command is used when the IP and MAC address binding is not working.
