### ISSUE TITLE
IRI: Could not find transactions by `findTransactions` API

### ISSUE THREAD

**Issue by ender503** [DLTcollab/general#193]
It is weird that could not get the transactions by using the `findTransactions` API.

The transaction can be found in the [TheTangle.org](https://thetangle.org/transaction/DHCBXQXRBVYLZPQ9KAWZ9FRXUQCHADDCW9BEIIZTWAOIQJCQIUKMNNUJSSNWDXD9SORVLGHKSGMK99999).

```bash
$ curl http://node0.puyuma.org:14265 \
-X POST \
-H 'Content-Type: application/json' \
-H 'X-IOTA-API-Version: 1' \
-d '{
  "command": "findTransactions",
  "addresses": [
    "DHCBXQXRBVYLZPQ9KAWZ9FRXUQCHADDCW9BEIIZTWAOIQJCQIUKMNNUJSSNWDXD9SORVLGHKSGMK99999"
  ]
}'
```

The `node0.puyuma.org:14265` is IRI load-balancer, the `node100.puyuma.org:14265` and `node.deviceproof.org:14265` return the same result.

**Comment by ender503** [comment]
@marktwtn could you help me trace this issue? 🙏

**Comment by marktwtn** [comment]
@ender503 I think you should not put the transaction hash in the addresses parameter.
Ref: [findTransactions API](https://docs.iota.org/docs/node-software/0.1/iri/references/api-reference#findtransactions)

**Comment by ender503** [comment]
Thanks for point out 🙈
