### ISSUE TITLE
CI: Fix the failure of the IRI regression test

### ISSUE THREAD

**Issue by marktwtn** [DLTcollab/general#194]
Our CI runs the **DLTcollab IRI** with the **IRI** regression test offered by IOTA.

However, it failed with the output message `[Neighbor Router] ERROR NeighborRouter:246 - error occurred in the neighbor router`.
On my desktop, the error does not happen.

**Comment by yillkid** [comment]
Could you describe the reproduce environment?  e.g. server domain name.

**Comment by marktwtn** [comment]
> Could you describe the reproduce environment? e.g. server domain name.

The error happens on the `node1`.

The steps would look like this:
- `$ git clone https://github.com/iotaledger/iri-regression-tests.git`
- `$ cd iri-regression-tests`
- `$ git clone https://github.com/DLTcollab/iri.git`
- `$ cd iri`
- `$ make check`
- `$ cd -`
- `$ bash -x run_all_stable_tests.sh [version]`. (The current version is **1.8.0-COACH**)

**Comment by marktwtn** [comment]
The verbose output message:
```
08/03 04:53:32.814 [Neighbor Router] ERROR NeighborRouter:246 - error occurred in the neighbor router
java.net.BindException: Address already in use
        at sun.nio.ch.Net.bind0(Native Method) ~[na:1.8.0_222]
        at sun.nio.ch.Net.bind(Net.java:433) ~[na:1.8.0_222]
        at sun.nio.ch.Net.bind(Net.java:425) ~[na:1.8.0_222]
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223) ~[na:1.8.0_222]
        at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74) ~[na:1.8.0_222]
        at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:67) ~[na:1.8.0_222]
        at com.iota.iri.network.NeighborRouter.route(NeighborRouter.java:176) ~[iri-1.8.0-COACH.jar:1.8.0-COACH]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_222]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_222]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_222]
```

I think the `Address already in use` problem is caused by the existed `IRI` running on node1.

**Comment by jserv** [comment]
Can we assign random port number for each IRI instance for CI purpose?

**Comment by marktwtn** [comment]
There are two new configuration in **IRI** version 1.8.0:
- NEIGHBORING_SOCKET_ADDRESS
- NEIGHBORING_SOCKET_PORT

The default value are written in `src/main/java/com/iota/iri/conf/BaseIotaConfig.java`.

The CI error did not happen in the past since the network configuration did not exist before version 1.8.0.
I'll send a pull request to the github repository: https://github.com/iotaledger/iri-regression-tests.

**Comment by marktwtn** [comment]
The **NEIGHBORING_SOCKET_PORT** works as the previous **TCP_RECEIVER_PORT** port, which is 15600 in default.
Hence the configuration is not a new one, it is just renamed.

The failure is caused by the **iri-regression-tests** since its new commit does not take care of the **TCP** port correctly.

**Comment by marktwtn** [comment]
According to the reply of the pull request: https://github.com/iotaledger/iri-regression-tests/pull/20
```
By the way we will deprecate those tests really soon,
once we merge in the instructions to run the new buildkite tests

Anyhows, when we will have the instructions for buildkite ready, I will close this PR.
```

It seems that the pull request won't be merged.
I'll fork the [iri-regression-tests](https://github.com/iotaledger/iri-regression-tests) and use it for our CI.
