### ISSUE TITLE
Correct IOTA full node information provided by community

### ISSUE THREAD

**Issue by jserv** [DLTcollab/general#195]
Community sites such as [IOTA Node List](https://iota-nodes.net/) provide partial listing of IOTA full node. However, some of them might be incorrect. For example, [IOTA Node List](https://iota-nodes.net/) mentions `node.deviceproof.org` as no SSL, that is not true. We shall communicate to IOTA community members to correct the full node information.

**Comment by jserv** [comment]
Check list: all attributes about PoW, SSL, and IRI versions.

**Comment by yillkid** [comment]
I found the account in discord (kevmiota#7421), and have sent message to him:

> Hi! 
I am the administrator of node.deviceproof.org on https://iota-nodes.net/, 
and found some incorrect attribute about the node as below,
could you correct the information for me? :-)
>
>1. SSL -> should be Yes (https://gist.github.com/yillkid/78241f8d738bc7470e1591ca2f64ab58)
>2. PoW -> should be Yes (https://gist.github.com/yillkid/5bff7d4a25a67912b3c3ae85aae7a132)

**Comment by yillkid** [comment]
> kevmiota今天 16:45
Hi there, thank you for your feedback. I'm currently on holidays. I ll check when I m back later this week

**Comment by yillkid** [comment]
Done.

![image](https://user-images.githubusercontent.com/185872/62988682-c959c500-be77-11e9-9b72-0efc54bb7949.png)
