### ISSUE TITLE
Base: Track transaction performance periodically with RAAM

### ISSUE THREAD

**Issue by jserv** [DLTcollab/general#198]
[raam.client.js](https://github.com/DLTcollab/raam.client.js) is a second layer data communication protocol for IOTA enabling protected data stream access and publishing, organized in so called channels. It is ideal for tracking transaction performance for each full node we are maintaining.

For example, you can execute `node examples/constructAndPublishLater.js` and wait for 2 messages being published. Typically, it takes about 20 seconds for `node.deviceproof.org` to generate RAAM channel, create 2 messages, and read from given channel. However, it takes a bit longer for `node10`, and `node1` is almost impossible to complete the above operation within 1 min.

Expected output:
1. Adopt examples from RAAM and execute them periodically with each full node;
2. Track the time for essential operations, especially for publishing and retrieving from Tangle;
3. Integrate into CI and/or health check system;

**Comment by jserv** [comment]
I have no idea why `node1` fails to complete RAAM operations. @marktwtn, does it imply the potential risks with RabbitMQ and FPGA cluster?

**Comment by ender503** [comment]
The problem is that `rabbitmq server` loss its configuration, so node1 IRI could not send do the remote PoW requests to the publish `rabbitmq server`.

The `rabbitmq-server` is based on it doesn't set the volume to preserve the configuration, so `rabbitmq-server` loss its configuration after restarting the `rabbitmq-server` container.

I fixed the docker problem and preserve the configuration on the `/opt/rabbbitmq-management`. 👌

**Comment by marktwtn** [comment]
It reveals the potential risk when **IRI + dcurl** do not connect with the **RabbitMQ  server** correctly.

When the **remote worker** does not work, the **dcurl** would fall back to local machine and do the PoW.
However, when the **RabbitMQ server** has some problem with **dcurl**, it never does the PoW and always returns false.

We should have a fall back mechanism when the **RabbitMQ server** is not working.

**Comment by jserv** [comment]
Since IRI has been deprecated, let's work on HORNET as on-going tasks.
