### ISSUE TITLE
Infra: Setup New FPGA boards

### ISSUE THREAD

**Issue by ender503** [DLTcollab/general#199]
The new FPGA boards have arrived, we need to set up them with some software, and then we could manage them with Ansible Playbook.

These steps need to set up on the scene.
- [x] Install the operating system
- [x] Statically assign MAC addresses and IP [#189](https://github.com/DLTcollab/general/issues/189)
- [x] Install `openssh-server` package

The following steps I could set up from remote
- [x] Setup user account, e.g. `fpga`, `user` or `ubuntu`
- [x] Install Python 2 (version 2.7) or Python 3 (versions 3.5 and higher)

**Comment by ender503** [comment]
This task is pending until we are sure there is a rack available or not.
If we don't have the rack, we may need to buy power-strip and ethernet cable.

**Comment by ender503** [comment]
After discussing with @jserv, we will set up them first, then move them if we have the rack to use.

**Comment by ender503** [comment]
Because we don't have enough ethernet ports for 8 x FPGA boards, we may need to buy another router. 
@yillkid could you provide the specification of the router? or which router you want to buy?

**Comment by yillkid** [comment]
> Because we don't have enough ethernet ports for 8 x FPGA boards, we may need to buy another router.
> @yillkid could you provide the specification of the router? or which router you want to buy?

Refer #201 for detail.

**Comment by marktwtn** [comment]
The default user account is `ubuntu`.

I used `$ sudo apt install openssh-server` to install the `openssh-server` package in the new image.
And I found out that the image already has **Python3** with version `3.6.7`.

**Comment by ender503** [comment]
The new smart switch has arrived, we need to set up it before continuing this issue.

**Comment by marktwtn** [comment]
The hardware and internet setup is done by @yillkid .
The **Playbook** management is handled by @ender503 .
And the preparation of **DE10-Nano** FPGA boards is done by @marktwtn .
