### ISSUE TITLE
Visualization of latest 10 milestone, confirmed tx and tips

### ISSUE THREAD

**Issue by yillkid** [DLTcollab/general#20]
In gitlab by @root on Dec 12, 2017, 00:30

*Created by: louielu*

Visulization of latest 10 mielstone, confirmed tx and tips can help people to understand the relationship between each milestone and tips.

**Comment by yillkid** [comment]
In gitlab by @root on Dec 12, 2017, 04:14

*Created by: yillkid*

Found a cool open source project [iota-dashboard](https://github.com/lsquires/iota-dashboard), simple but powerful!

- [demo site](http://node0.puyuma.org:3000/)

**Comment by yillkid** [comment]
In gitlab by @root on Dec 12, 2017, 13:33

*Created by: louielu*

This is awesome!

**Comment by yillkid** [comment]
In gitlab by @root on Dec 12, 2017, 14:14

*Created by: louielu*

Some problem about `iota-dashboard`:

1. Settings is somehow painful...
  * No setting files (manual fix the code)
  * No documentation
2. Timeline design will let the diagram floating around, e.g. 1 min, when a tx is out of the 1 min range, it will disappear in the graph, reposition tangle.

3. The direction isn't quite useful. it only gives one verification link, and most of the tips didn't have the direction to two other tx. Not sure if it is because of export didn't contain that tx. 

Conclusion: not as useful as I think, but it provides a template to improve.

**Comment by yillkid** [comment]
In gitlab by @root on Dec 26, 2017, 02:54

*Created by: yillkid*

How about this tool: https://bl.ocks.org/mbostock/4062045

The idea is just export the transactions we interested to a JSON format (e.g: a_double_spend_example.json), then we can discuss with a visualize sub-tangle output.

**Comment by yillkid** [comment]
In gitlab by @root on Jan 10, 2018, 18:29

assigned to @louielu

**Comment by jserv** [comment]
We can host web-based tools such as [iota-dashboard](https://github.com/lsquires/iota-dashboard) on `node0` or `node10`, and then @KevinKu might benefit from it when analyzing how Tangle works in details.

**Comment by jserv** [comment]
Discard the old fashions.
