### ISSUE TITLE
Buy a smart switch

### ISSUE THREAD

**Issue by yillkid** [DLTcollab/general#201]
Requirement:

1. 16 ports at least: 12 FPGA boards and 4 servers
2. VLAN: To plan the virtual local area network for loading balancing
3. DHCP: Management IP and VLAN for target boards and servers
4. Rack-mounted: For hardware deploy policy

Expected purchase:

- [D-Link DGS-1210-28](https://24h.pchome.com.tw/prod/DRAF6A-A66157845?fq=/S/DSBA1P).

**Comment by ender503** [comment]
The `D-Link DGS-1210-28` already sent to NCKU. 👌
