### ISSUE TITLE
Infra: Setup Smart Switch

### ISSUE THREAD

**Issue by ender503** [DLTcollab/general#203]
We will use the new D-Link DGS-1210-28 switch([#201](https://github.com/dltcollab/general/issues/201)) to replace the ASUS RT-AC1300GPLUS.

The D-Link DGS-1210-28 switch should contain the following settings:
- [x] WAN - Internet Connection
- [x] Manually Assigned IP around the DHCP list (node0 and FPGAs)
- [x] Port Forwarding List

**Comment by marktwtn** [comment]
@yillkid has finished the setup.
