### ISSUE TITLE
Deploy chronicle on node8

### ISSUE THREAD

**Issue by yillkid** [DLTcollab/general#211]
Deploy [chronicle](https://github.com/iotaledger/chronicle) on node8 and write a deploy guide.

- Github repository
  - [chronicle](https://github.com/iotaledger/chronicle)

- TODO
  - Deploy  chronicle
  - Merge with all snapshot files
  - Discussing items with IF

- Note
  - [Chronicle delopy note](https://hackmd.io/@DsnbUcX9Tyi-Vn5MNyBM7g/By0rpa-vS)

**Comment by yillkid** [comment]
Now we can fetch IOTA history transaction hash and trytes by Chronicle API as below:

- Request
```
curl http://127.0.0.1:4000/api \
-X POST \
-H 'Content-Type: application/json' \
-H 'X-IOTA-API-Version: 1' \
-d '{
"command": "getTrytes",
"hashes": ["OYHIBAJHIPIMSWTARLZMUDEOMCLUGDVIHSMTZKTLLKJDCOKDTLTQRI9YWNQLDDDXOBUUMQOFISA999999"]
}'
```
- Response
```
{"trytes":[{"address":"KPWCHICGJZXKE9GSUDXZYUAPLHAKAHYHDXNPHENTERYMMBQOPSQIDENXKLKCEYCPVTZQLEEJVYJZV9BWU","attachmentTimestamp":null,"attachmentTimestampLowerBound":null,"attachmentTimestampUpperBound":null,"branchTransaction":"ESVEN9ZFGRXQXPMXEKCEKFOEEENYQZONGHWQFY9WZABKMULSKL9DZTAMQEAFUMNMPDIDCAUAZPC999999","bundle":"RADCCDMEKWYHQLFYVLTTFMDCACBQNKAUGGUX9YUXBLOIJRSEIHJZUWESSEBCHAYOYFZORQAHHGXDVDCKK","currentIndex":0,"lastIndex":1,"nonce":"WKR9ZVSILWCAHMBOBKDCFVMYVGRBJDNTAPEFFTFZIVHOUEIGQKADMXBVROKF9JFBZFHTDMRZUBFBJWAMR","obsoleteTag":"FFH999999999999999999999999","signatureMessageFragment":"IHWBOXGKKUZDSSMVJKXGEQDSNWREWQROJFWFPFIGHDSRHOZTDBYZPAQQDQCIASONKDWMULCHMYWKDLGPAMFVIPRIWOUWCAYGPWOCI9QKGQNDJVNGGWGQSLIFJGJOKIZPUAXPINEYYHCVSSBFQPPQLWXBCCSPWWHVERTDALI9UNPZGIY9DD9VEDIABNLAJZZJPXERSISFGGHOUAQCKUBOJPRCOVPVXJJOGGWBOAZLI9QH9B9NYLKXITTBH9MQMFZYZUZFKGC9VQKN9KA9XDQZMBABOT9ARLMIXQHWARWMB9UIDRYRC9SSKYEYUNX9SGDSNXTA9LDJOWZUVKBYYBPUGSMIONX9LFNOKYDVEMNCAGCOGNOTUNZKSPOUVPHLGIMQMQGIUPIBGLVERWWGMINITAYVWLKMPVMZ9B9HNXAW9ZP9UWCRNQOLSPKMYZJVLRHQVNVFHFVIQFOY9UBYMRLLEKAGITQNJIZNFYDY9OPJYHFJHCRUTEWXZUQEHLUSYPHXIGL9YPRXIUTGCD9JUAJUZ9TX9XPTWCDO9ULRJ9DXENRFLWCSAZJDDFMFFHGQCQZGIHOOI9KCQBCRDIWJ9YRWLHIJJMVRAY9VAHJYOAATYHRFMICKSIPVHLFRSGVGIWAJMUEUVYYVWITTVZPYKVTVLNIXCPRSFURPHWYHUCWGGMDPDQWCQJSBPBHWQVZNLBQUHDDTNVPPRPMSQKXQPIDQUF9SCVAYEQDGPQUVIYEOWIXATHYHJTOSQACGSGTHVYOXKWZ9YRWTYTJXPLIOTUWRZARSVVHYQQIGDYWERZXGXKRPQIKSODGHKEPIZDACHPRPGXHXAZOAMBFYCRHLMWIIBQLJQEMJXLRMIPCDNJRMJGMMOGBIOOIBVLFUPYTVEXRTYGJZBQHPJGIMCOUBANBVNMBQ9CWDJHGQNI9VNTJSBEVMFJMFOZBCFZKQDIHGZYQCETPYGHNUYAYXVWMXHVOKKZBCVZTLWZKFDNEREJMHSNWITMAK9MQTQNZQKFALHQDQKSSFJOZSBXHEIIIJZNASEJGSNJNMRPHGCQISQHH9REONLGQTASNQLH9TOMGRNWPDVQIZGQZBRAGWNOJW9VENZW9OMBUUYKSKGBVRZ9AZAPIJFZWEODMQFLSRCERSWCDWBJFTONVUAZMXUCARUWETEUDJIBLVKKBBIUFGWQUMM9OXTTWMPZZPFKPJDPTYPKTWFNAABXLYZJIKBQVHL9NPORO9TLJQABI9XPLQHVSDTZQCPURIPGSPIAFETQIHHEXBRSLXDIYIMEGTUVDSUVKZ9MXAWJNMQPZRCZV9OL9GIKPCYWYLUMAIMRJZILULMYRTFURGRBCUVTRTODANEJINQAPLNKFUDSPBAT9QDEVJPCZMHQZTYDRYA9AIETUN9JDOYJZGZMOONR9WAEXWHEO9AMENRKWEWIDNBMTMYWFUZBQXMTMLC9DNS9FQG9ZPL9HH9TLBPOGDBZCHXVXNNWNHBNZJWNVIYHFSCBDWVE9KJHZMPHT9HBQEIGVOPPQAFQZDVLWKALLHEXOZAFHPQPXIXZUIHBRD9FWIYRZ9BXMWNZQWOB9RENQJNGJYHRQCUPNETKBPHVPLNMVMLOOHFXFUWOFBPSKYV9ZCDEIUOOWFNCSRDZP99WYQHSODFQXOPZ9XMROIUGPBRUJOBGMFRXJSNHAKSCFFOB9OVD9BUKEOLYVRVKZPBUKCBFCX9ROWIKDAYZQZDRPRQPE9FTWWVPEZXE9CITNR9WOGXAZJKP9AQHWKKSZGLYFGCZFGPTYY9MCCXEYWYEXBWADKR9V9VMPGTIGWSZMP9WBQQPSUVLRA9TCYYYCIFJLX9OXZGZCXMKPRDGGFQMITAJJLZBTMBZXZPXPEXGNWEUXBOMWNJZRMNODDTNICUDTCNJUCYVSDDPIGKQZAWVATWNLZPIZUFEYUIVPZZWDGCTZCVE9YJAEIYTDWY9HCONHSILZUXWQKRHOGVFHDLLURLDNSKDTBVYXJOAAFZYMHECNIZUAWPBZUXRSXCWMMJXZBFVHBCYNMVVUJHZANICNSEWLRANHALZCZINVKJG9YORFJDRPTLRTJ9PQHNQDKSBNBLSONTU9PKFRMUCCJCT9LOTOKLLFPSMRGSZGHVLA9LSDBVIHLWNPVSOFBRH9PHHHOIXVXQCMQDELUICCAJZCPTCM","snapshotIndex":6000,"tag":null,"timestamp":1480161224,"trunkTransaction":"SJTDXDHHBY9LXEFNLURWLXYGZMAUWBRVOFFGEOEFZIVGIEWASDUHVVQPC9FLSQWCSWLRTYMRLMW999999","value":0}]}
```

Read the [deploy document](https://hackmd.io/@DsnbUcX9Tyi-Vn5MNyBM7g/By0rpa-vS) for detail.

But we got a problem when receive the new transaction by ZMQ:
```
03:35:48.055 [warn] Wasn't able to collect bundle: IOMWTWEZEPFIGY9URFLAOYKVIBBKYFHTE9JAQFLKSLXPBFG9AK9YYPOSTVVWFFPTLCQPVPYOBMAS99999
03:36:33.184 [warn] Wasn't able to collect bundle: KVQDDXHMEDSETWRIJGR9YWHPOCJNKVDLFEFCFCXY9QILOHFPSO9R9KBRWAAWAXKHQLQFENUPNKNGZ9999
03:37:53.068 [warn] Wasn't able to collect bundle: QYSLSNISKQAUZDMBDUTTKEWLMHBSTL9BOAFTDYH9MOYMKDGNBAYAQUJPAGTBOAQXRRSTWWEV9VUUZ9999
03:39:23.308 [warn] Wasn't able to collect bundle: EAFKDAACCNYLSWHJWXQAANDBSYTTABXCXBEVROYHJSPLTLTKFXPBYGELRVXEETGUVM9HAXNQHCQIZ9999
03:39:49.479 [warn] Wasn't able to collect bundle: UZCYNW9QFGTFJXJQEEWNZKINOTDSNAPAOIJZQBURSNJSDCLDEKJIMKCN9OUDPXFNGPHPAYICQHRKA9999
03:40:19.150 [warn] Wasn't able to collect bundle: XJFFDVTISYYOGXPUWPA9PJQZIQZ9IENDHABRRM9ASSGGAKFHJQOJZMD9JDUCVH9OOVQYWGQYUJ9IA9999
03:40:42.173 [warn] Wasn't able to collect bundle: RVLWEBSIXEHNZFNBDFOBUFO9NMTHQUFR9NDCBTK9BLJM9QXUHIXG9LNHW9QSYGXBHIWJZYRSXXAT99999
03:41:36.441 [warn] Wasn't able to collect bundle: GBTTADCUMWIXK9QJZRGMJWRPVRRHFHOTTLERXWGOLGHIZFOXSOEWDCZKENWDCPDJGRXDSKKL9KYGZ9999
03:41:37.062 [warn] Wasn't able to collect bundle: BCB9KYFETTIDYTQPQNWDTOMTJLFTSTVITSXVYTMDH9ORTNMIHPODQGLYLDQMLKDKMTWAGREHBOXPA9999
03:43:01.525 [warn] Wasn't able to collect bundle: RYM9EUGVQVIGMQFYBPWAZTPIJTMMEAMPFGQRGVEZCYDUCOLFTPBOKCDKVIACRICCDP9JAWGBCLHDA9999
03:43:43.399 [warn] Wasn't able to collect bundle: QCIXUEOTBSLEFJCUADEEBPYXOFZDDQTGARKB9YFPWCGODZINXQGJBNQBDTOXVMVGNWDFHJWYBCBQ99999
```

I will create a new issue to trace it.

**Comment by locke2833** [comment]
I am wondering the Chronicle had succeeded import dump files.
Did you see the following log after starting th Chronicle?

> When Chronicle starts, you should see the imported the last dmp 'milestone' file message. When you see this message, you can check that the import was successful by opening the dmps.txt file and seeing that it's empty.

I found the dmps.txt file is not empty.
And the disk usage is too small than recognize after import 7xx GB data.
`/var/lib$ sudo du -sh scylla
2.2G	scylla
`

**Comment by jserv** [comment]
Is it possible to prepare SquashFS file system image on `node10` and then transfer to `node8`? SquashFS supports efficient compression algorithms, which fit the storage usage.

**Comment by jserv** [comment]
Since we have powerful processors, we shall not waste their capabilities.

**Comment by locke2833** [comment]
> Now we can fetch IOTA history transaction hash and trytes by Chronicle API as below:
> 
> * Request
> 
> ```
> curl http://127.0.0.1:4000/api \
> -X POST \
> -H 'Content-Type: application/json' \
> -H 'X-IOTA-API-Version: 1' \
> -d '{
> "command": "getTrytes",
> "hashes": ["OYHIBAJHIPIMSWTARLZMUDEOMCLUGDVIHSMTZKTLLKJDCOKDTLTQRI9YWNQLDDDXOBUUMQOFISA999999"]
> }'
> ```
> 
> * Response
> 
> ```
> {"trytes":[{"address":"KPWCHICGJZXKE9GSUDXZYUAPLHAKAHYHDXNPHENTERYMMBQOPSQIDENXKLKCEYCPVTZQLEEJVYJZV9BWU","attachmentTimestamp":null,"attachmentTimestampLowerBound":null,"attachmentTimestampUpperBound":null,"branchTransaction":"ESVEN9ZFGRXQXPMXEKCEKFOEEENYQZONGHWQFY9WZABKMULSKL9DZTAMQEAFUMNMPDIDCAUAZPC999999","bundle":"RADCCDMEKWYHQLFYVLTTFMDCACBQNKAUGGUX9YUXBLOIJRSEIHJZUWESSEBCHAYOYFZORQAHHGXDVDCKK","currentIndex":0,"lastIndex":1,"nonce":"WKR9ZVSILWCAHMBOBKDCFVMYVGRBJDNTAPEFFTFZIVHOUEIGQKADMXBVROKF9JFBZFHTDMRZUBFBJWAMR","obsoleteTag":"FFH999999999999999999999999","signatureMessageFragment":"IHWBOXGKKUZDSSMVJKXGEQDSNWREWQROJFWFPFIGHDSRHOZTDBYZPAQQDQCIASONKDWMULCHMYWKDLGPAMFVIPRIWOUWCAYGPWOCI9QKGQNDJVNGGWGQSLIFJGJOKIZPUAXPINEYYHCVSSBFQPPQLWXBCCSPWWHVERTDALI9UNPZGIY9DD9VEDIABNLAJZZJPXERSISFGGHOUAQCKUBOJPRCOVPVXJJOGGWBOAZLI9QH9B9NYLKXITTBH9MQMFZYZUZFKGC9VQKN9KA9XDQZMBABOT9ARLMIXQHWARWMB9UIDRYRC9SSKYEYUNX9SGDSNXTA9LDJOWZUVKBYYBPUGSMIONX9LFNOKYDVEMNCAGCOGNOTUNZKSPOUVPHLGIMQMQGIUPIBGLVERWWGMINITAYVWLKMPVMZ9B9HNXAW9ZP9UWCRNQOLSPKMYZJVLRHQVNVFHFVIQFOY9UBYMRLLEKAGITQNJIZNFYDY9OPJYHFJHCRUTEWXZUQEHLUSYPHXIGL9YPRXIUTGCD9JUAJUZ9TX9XPTWCDO9ULRJ9DXENRFLWCSAZJDDFMFFHGQCQZGIHOOI9KCQBCRDIWJ9YRWLHIJJMVRAY9VAHJYOAATYHRFMICKSIPVHLFRSGVGIWAJMUEUVYYVWITTVZPYKVTVLNIXCPRSFURPHWYHUCWGGMDPDQWCQJSBPBHWQVZNLBQUHDDTNVPPRPMSQKXQPIDQUF9SCVAYEQDGPQUVIYEOWIXATHYHJTOSQACGSGTHVYOXKWZ9YRWTYTJXPLIOTUWRZARSVVHYQQIGDYWERZXGXKRPQIKSODGHKEPIZDACHPRPGXHXAZOAMBFYCRHLMWIIBQLJQEMJXLRMIPCDNJRMJGMMOGBIOOIBVLFUPYTVEXRTYGJZBQHPJGIMCOUBANBVNMBQ9CWDJHGQNI9VNTJSBEVMFJMFOZBCFZKQDIHGZYQCETPYGHNUYAYXVWMXHVOKKZBCVZTLWZKFDNEREJMHSNWITMAK9MQTQNZQKFALHQDQKSSFJOZSBXHEIIIJZNASEJGSNJNMRPHGCQISQHH9REONLGQTASNQLH9TOMGRNWPDVQIZGQZBRAGWNOJW9VENZW9OMBUUYKSKGBVRZ9AZAPIJFZWEODMQFLSRCERSWCDWBJFTONVUAZMXUCARUWETEUDJIBLVKKBBIUFGWQUMM9OXTTWMPZZPFKPJDPTYPKTWFNAABXLYZJIKBQVHL9NPORO9TLJQABI9XPLQHVSDTZQCPURIPGSPIAFETQIHHEXBRSLXDIYIMEGTUVDSUVKZ9MXAWJNMQPZRCZV9OL9GIKPCYWYLUMAIMRJZILULMYRTFURGRBCUVTRTODANEJINQAPLNKFUDSPBAT9QDEVJPCZMHQZTYDRYA9AIETUN9JDOYJZGZMOONR9WAEXWHEO9AMENRKWEWIDNBMTMYWFUZBQXMTMLC9DNS9FQG9ZPL9HH9TLBPOGDBZCHXVXNNWNHBNZJWNVIYHFSCBDWVE9KJHZMPHT9HBQEIGVOPPQAFQZDVLWKALLHEXOZAFHPQPXIXZUIHBRD9FWIYRZ9BXMWNZQWOB9RENQJNGJYHRQCUPNETKBPHVPLNMVMLOOHFXFUWOFBPSKYV9ZCDEIUOOWFNCSRDZP99WYQHSODFQXOPZ9XMROIUGPBRUJOBGMFRXJSNHAKSCFFOB9OVD9BUKEOLYVRVKZPBUKCBFCX9ROWIKDAYZQZDRPRQPE9FTWWVPEZXE9CITNR9WOGXAZJKP9AQHWKKSZGLYFGCZFGPTYY9MCCXEYWYEXBWADKR9V9VMPGTIGWSZMP9WBQQPSUVLRA9TCYYYCIFJLX9OXZGZCXMKPRDGGFQMITAJJLZBTMBZXZPXPEXGNWEUXBOMWNJZRMNODDTNICUDTCNJUCYVSDDPIGKQZAWVATWNLZPIZUFEYUIVPZZWDGCTZCVE9YJAEIYTDWY9HCONHSILZUXWQKRHOGVFHDLLURLDNSKDTBVYXJOAAFZYMHECNIZUAWPBZUXRSXCWMMJXZBFVHBCYNMVVUJHZANICNSEWLRANHALZCZINVKJG9YORFJDRPTLRTJ9PQHNQDKSBNBLSONTU9PKFRMUCCJCT9LOTOKLLFPSMRGSZGHVLA9LSDBVIHLWNPVSOFBRH9PHHHOIXVXQCMQDELUICCAJZCPTCM","snapshotIndex":6000,"tag":null,"timestamp":1480161224,"trunkTransaction":"SJTDXDHHBY9LXEFNLURWLXYGZMAUWBRVOFFGEOEFZIVGIEWASDUHVVQPC9FLSQWCSWLRTYMRLMW999999","value":0}]}
> ```

This is the first transaction in 6000.dmp （which means snapshot index from 0~6000)
I tried another transaction hash as following. 
```
curl http://127.0.0.1:4000/api \
-X POST \
-H 'Content-Type: application/json' \
-H 'X-IOTA-API-Version: 1' \
-d '{
"command": "getTrytes",
"hashes": ["99999JFROHHXUGDPQCPITXJFJBOSOVDQJMMGZACX9OMUIDJRJE9FM9O9UPMIPDAZWNGPBGWTQLJAA9999"]
}'
```
and got following response
`{"trytes":[null]}`

`99999JFROHHXUGDPQCPITXJFJBOSOVDQJMMGZACX9OMUIDJRJE9FM9O9UPMIPDAZWNGPBGWTQLJAA9999` is the first transaction hash in 61491.dmp

But this transaction could be found in TheTangle.
https://thetangle.org/transaction/99999JFROHHXUGDPQCPITXJFJBOSOVDQJMMGZACX9OMUIDJRJE9FM9O9UPMIPDAZWNGPBGWTQLJAA9999

**Comment by locke2833** [comment]
I test this because when I imported the dump files, it uses much more space than the Chronicle in node 8. I am wondering I miss something important for optimization. 
I would like to restart the Chronicle in node8 and have some tests.

**Comment by locke2833** [comment]
After testing, the Chronicle did not import dump files successfully.
I restarted the Chronicle and confirmed the following description.

> When Chronicle starts, you should see the imported the last dmp 'milestone' file message. When you see this message, you can check that the import was successful by opening the dmps.txt file and seeing that it's empty.

But all files in the import list did not completely be imported.
There's a relate issue. https://github.com/iotaledger/chronicle/issues/6

**Comment by LouayKamel** [comment]
Hey guys, please follow this as mentioned in iotaledger/chronicle#6 : 
- drop tangle keyspace from scylladb
- clone new chronicle
- start chronicle
