### ISSUE TITLE
Permanode: Trust of historical data and consistency

### ISSUE THREAD

**Issue by locke2833** [DLTcollab/general#212]
### Description

Since IOTA foundation release dumped files of historical transactions. There's need a way to verify the correctness and ensure we have full data in our database.

**Comment by jserv** [comment]
Time to close?

**Comment by locke2833** [comment]
Chronicle Elixir receives confirmed transactions by ZMQ client. 
Once it finds that some transactions are missed in the bundle of transactions it received, it will fetch the missing transactions from IRI.

According to IF 2020 [roadmap of Permanode ](https://roadmap.iota.org/permanode)
The "Permanode runtime based on the Tokio Rust crate, plans to release in 2020 Q1.
It is supposed to be better than Cornicle Elixir. For further details, we need to discuss it with IF developers.
