### ISSUE TITLE
Automate the deployment of IRI service with preload data 

### ISSUE THREAD

**Issue by yillkid** [DLTcollab/general#220]
Write a script to deploy IRI service launch with preload data (local snapshot file and basic neighbors)

**Comment by yillkid** [comment]
@JulianATA :
1. The IRI deploy on `node1:/home/julian/iri`
2. Start IRI service ``` $ sudo systemctl start iri-julian.service ```
3. Stop IRI service ``` $ sudo systemctl stop iri-julian.service ```

Neighbors:
- tcp://node11.puyuma.org:14265

Syncing:
- 1050000/1202613

It's a syncing IRI (means IRI will load sub-Tangle on memory, but not whole), 
not sure it's a suitable testing environment or not.
If you need a fully-synced IRI service, let me know, please.

- Port enable
  - PORT = 14266
  - NEIGHBORING_SOCKET_PORT = 15601

**Comment by ender503** [comment]
Updated the related documents. 👌
