### ISSUE TITLE
Setup ScyllaDB Monitoring Stack: Real-Time Database Monitoring System

### ISSUE THREAD

**Issue by locke2833** [DLTcollab/general#227]
[Scylla Monitoring Stack description](https://www.scylladb.com/product/scylla-manager/#scylla-monitoring-stack) 

- Installed along with Prometheus and Grafana
- A number of predefined dashboards
- Display latencies, cache hits, throughput, disk activity and more.

[github](https://github.com/scylladb/scylla-monitoring)

**Comment by ender503** [comment]
Let me know if there is something I could help with. 😃

**Comment by locke2833** [comment]
I've successfully run the Scylla monitor alone with Prometheus and Grafana which connects to a Scylla cluster in my local machine.
I will discuss with @ender503 on integrating to the existing Promotheus and Grafana infrastructure in our server.

![image](https://user-images.githubusercontent.com/3009797/68624686-5ca3a480-0512-11ea-8591-51c5ff1d3930.png)

**Comment by ender503** [comment]
After discuss with @locke2833, I'll try to integrate with the existing Prometheus and Grafana. 👍

**Comment by jserv** [comment]
Always call it `ScyllaDB` instead of `Scylla`. We might refer "scylla" to certain project names.

**Comment by ender503** [comment]
ScyllaDB Dashboards are already set up on our Grafana Dashboard. 
![image](https://user-images.githubusercontent.com/1849431/69232456-0e536d00-0bc6-11ea-8792-02213883da7e.png)

![image](https://user-images.githubusercontent.com/1849431/69232483-18756b80-0bc6-11ea-8248-0274700be028.png)
