### ISSUE TITLE
Infra: Setup FPGA borads and IRI on NCTU

### ISSUE THREAD

**Issue by ender503** [DLTcollab/general#228]
Expected Output:
- [x] Setup 2x FPGA boards MAC and IP address
- [x] Create RabbitMQ VM on node10.
- [x] Setup `IRI` for FPGA on RabbitMQ VM.
- [x] Setup `rabbitmq-management` on the RabbitMQ VM
- [x] Setup `rabbitmq-exporter` on the RabbitMQ VM
- [x] Setup `Prometheus` to get the NCTU RabbbitMQ infromation.

**Comment by marktwtn** [comment]
I have assigned the MAC address with the value `74:74:74:74:74:01` and `74:74:74:74:74:02`.
And the IP and MAC mapping will be handled by @ender503 .

**Comment by ender503** [comment]
@yillkid, I need your help to move the IRI from LXC VM(.105) to KVM(.106).

**Comment by yillkid** [comment]
> @yillkid, I need your help to move the IRI from LXC VM to KVM.

done and fully-synced.

```
{
    "appName": "IRI",
    "appVersion": "1.8.2-COACH",
    "coordinatorAddress": "EQSAUZXULTTYZCLNJNTXQTQHOMOFZERHTCGTXOLTVAHKSA9OGAZDEKECURBRIXIJWNPFCQIOVFVVXJVD9",
    "duration": 0,
    "features": [
        "dnsRefresher"
    ],
    "jreAvailableProcessors": 16,
    "jreFreeMemory": 380129736,
    "jreMaxMemory": 2328363008,
    "jreTotalMemory": 1475870720,
    "jreVersion": "1.8.0_222",
    "lastSnapshottedMilestoneIndex": 1272913,
    "latestMilestone": "SLNGEGAMPHGKAMLUEYJPYXPMHCTHAAKJAMSXIDPRXCXMLCANWQYQVFBXWXDHPIWFSXGTDNYY9VAGA9999",
    "latestMilestoneIndex": 1273014,
    "latestSolidSubtangleMilestone": "SLNGEGAMPHGKAMLUEYJPYXPMHCTHAAKJAMSXIDPRXCXMLCANWQYQVFBXWXDHPIWFSXGTDNYY9VAGA9999",
    "latestSolidSubtangleMilestoneIndex": 1273014,
    "milestoneStartIndex": 1269570,
    "neighbors": 3,
    "packetsQueueSize": 0,
    "time": 1576036890132,
    "tips": 2932,
    "transactionsToRequest": 0
}
```

**Comment by ender503** [comment]
I replaced `iri-1.8.2-COACH.jar` with `iri-1.8.2-COACH-REMOTE.jar` and connected the IRI to the `rabbitmq-management`.

**Comment by ender503** [comment]
I will setup the 2 x FPGA boards on NCTU this Friday.
