### ISSUE TITLE
HORNET evaluation

### ISSUE THREAD

**Issue by jserv** [DLTcollab/general#232]
[HORNET](https://github.com/gohornet/hornet) is a lightweight alternative to IOTA's fullnode software “IRI”, and we would like to understand the benefit from the reduction of needed resources while significantly increasing the performance.

Expected output:
1. Run HORNET on a usual PC and analyze its system utilization;
2. Check the interconnectivity between HORNET and IRI;

**Comment by yillkid** [comment]
It's OK of [running HORNET on my laptop](https://hackmd.io/@DsnbUcX9Tyi-Vn5MNyBM7g/Hkc7LrtCH), and I will:

1. Close this issue
2. Create an EPIC for describing the testing plans
3. The issues of the EPIC as below:  

- Action items
  - Install HORNET on RPi 4
  - Create a VM on node10, the HW specification same with `iri-experimental`
    - Install HORNET on `iri-experimental`
  - Install HORNET on `RPi 4`
  - The HW consumption
    - Compare the HW consumption
      - Memory usage on fully-synced
      - CPU usage on PoW
  - APIs
    - Compare the duration of APIs

**Comment by yillkid** [comment]
Evaluate the performance of HORNET #233
