### ISSUE TITLE
Evaluate the performance of HORNET

### ISSUE THREAD

**Issue by yillkid** [DLTcollab/general#233]
- Install on different HW
  - Install HORNET on `de10-Nano`
  - Install HORNET on `RPi 4`
  - Create a VM on node10, the HW specification same with `iri-experimental`
    - [x] Install HORNET on `iri-experimental` #234
- Hornet study
  - Study HORNET configuration #235
- The HW consumption
  - Compare the HW consumption on fully-synced
    - Memory usage on fully-synced #238 
    - CPU usage on PoW
- APIs
  - Compare the duration of APIs

**Comment by jserv** [comment]
Let's move forward.
