### ISSUE TITLE
Study HORNET configuration

### ISSUE THREAD

**Issue by yillkid** [DLTcollab/general#235]
The setting of HORNET is very different from IRI, they will affect the completion of the ledger or the confirmation rate of new transactions (tips). There is a config example as below need to study:

- [config.json](https://github.com/gohornet/hornet/blob/master/config.json)

**Comment by JulianATA** [comment]
## profiles.custom
### caches
>Despite HORNET using the same tip selection algorithm as IRI, HORNET is still way faster than IRI due to improvements done on the implementation level.

* **requestQueue:** A queue to catch requests like 'STING', approves, milestone ...in [request.go](https://github.com/gohornet/hornet/blob/c63f3751e50548cf5c60e479a57992e490c2c6a9/plugins/gossip/requests.go)
---
reference to [cache](https://godoc.org/github.com/m3db/m3metrics/matcher/cache).
* **approvers:** Ordinary cache for approvers.
* **bundles:** Ordinary cache for bundles
* **milestones:** Ordinary cache for milestones
* **spentAddresses:** Ordinary cache for spentAddresses.
* **transactions:** Ordinary cache for transactions.

**size:** refer to `capcity`
**evictionSize** refer to `EvictionBatchSize`

---
* **incomingTransactionFilter:** A lru cache for pending requests in `packet_processor.go`.
* **refsInvalidBundle:** Memorize a certain transaction reference an invalid bundle. Accelerates the process of `tips selection` and ` consistency check `.

### [badger](https://godoc.org/github.com/dgraph-io/badger)
> Fast key-value DB in GO based on [log-structure merge tree](https://en.wikipedia.org/wiki/Log-structured_merge-tree).
> This part sets a badgerDB mainly for [recovery](https://github.com/gohornet/hornet/search?q=badger&unscoped_q=badger).

**Comment by JulianATA** [comment]
## tipsel
* **belowmaxdepthtransactionlimit:**
    * **BelowDepthMemoizationCache:** Keeps track of whether a tx is below the max depth for the given milestone.
* **maxdepth:** The maximum depth can travel.

**Comment by JulianATA** [comment]
### mqtt broker in Hornet
Broker using [fhmq/hmq](https://github.com/fhmq/hmq/)
* **/plugins/mqtt/topics.go** 
    * define topics(event topics)
* **/plugins/mqtt/parameters.go**
    * set parameters by configuration
* **hornet/plugins/mqtt/events.go**
    * onNewTx
        * publishTx
        * publishTxTryTes
    * onConfirmedTx
        * publishConfTx
    * onNewLatestMilestone
        * publishLMI
        * publishLMHS
    * onNewSolidMilestone
        * publishLMS
* All of publish functions are based on broker.Send()
    * publishLMI
```go
func publishLMI(lmi milestone_index.MilestoneIndex) error {

	err := mqttBroker.Send(topicLMI, fmt.Sprintf(`{"prevLMI":"%d","lmi":%d,"timestamp":"%s"}`,
		prevLMI, // Index of the previous solid subtangle milestone
		lmi,     // Index of the latest solid subtangle milestone
		time.Now().UTC().Format(time.RFC3339)))

	// Update previous milestone index
	prevLMI = lmi

	return err
}
```
* **hornet/plugins/mqtt/broker.go**
    * NewBroker
    * Start
    * Shutdown
    * Send

### mqtt_config.json
Broker using [fhmq/hmq](https://github.com/fhmq/hmq/)
* **workerNum:** Worker num to process message, perfer (client num)/10. (default 1024)
* **port:** Use port for clients (default: 1883)
* **host:** Network host to listen on. (default "0.0.0.0")
* **cluster:**(optional) 
    * **host:**
    * **port:**
* **router:**
* **wsPort:** Use port for websocket monitoring
* **wsPath:** Use path for websocket monitoring
* **wsTLS:** if using TLS for websocket monitoring
* **tlsPort:** The encrypted alternate of tcp
* **tlsHost:** The encrypted alternate of tcp
* **tlsInfo:** The encrypted alternate of tcp, included `caFile, `certFile`, `keyFile`

* **plugins:** plugins like `Auth Connect`, `Auth ACL`, `Cache Support` for Auth.

### Quality of Service:
* **QoS: 0** At most once (fire and forget) 
![Untitled Diagram (18)](https://user-images.githubusercontent.com/37362730/74241405-eda73900-4d16-11ea-862a-5d9bfdd644a7.png)

* **QoS: 1** At least once
    * PUBACK: publish acknowledgemen
![Untitled Diagram (17)](https://user-images.githubusercontent.com/37362730/74241409-f0099300-4d16-11ea-93fb-430b4047e532.png)

* **QoS: 2** Exactly once
    * PUBREC: publish received
    * PUBREL: publish release
    * PUBCOMP: publish complete
![Untitled Diagram (19)](https://user-images.githubusercontent.com/37362730/74241420-f861ce00-4d16-11ea-9e3d-64961ca7e989.png)

**Comment by jserv** [comment]
@JulianATA, after collecting the materials into single page / wiki, you can close this issue.

**Comment by JulianATA** [comment]
@jserv, the informations are collected to a [page](https://hackmd.io/@hPMCWajOS-ORQdEEAQ04-w/SkdxayP08) and updated to v0.4.1-rc4.  The placement of the page will be discussed.
