### ISSUE TITLE
Base: Rebase DLTcollab IRI to version 1.8.4

### ISSUE THREAD

**Issue by ender503** [DLTcollab/general#236]
As the IRI releases version 1.8.3, the DLTcollab IRI should be rebased to update the code.
And releases **v1.8.3-COACH** and **v1.8.3-COACH-REMOTE** for deployment.

Version 1.8.3 release page: https://github.com/iotaledger/iri/releases/tag/v1.8.3-RELEASE
Hotfix in v1.8.4: https://github.com/iotaledger/iri/releases/tag/v1.8.4-RELEASE

**Comment by jserv** [comment]
[IRI-1.8.4](https://github.com/iotaledger/iri/releases/tag/v1.8.4-RELEASE) is out with hotfix. Let's bump.

**Comment by marktwtn** [comment]
The update is done.
Please check the release page to acquire the corresponding JAR file.

Release page: [DLTCollab/viri-1.8.4-COACH](https://github.com/DLTcollab/iri/releases/tag/v1.8.4-COACH)
