### ISSUE TITLE
Update IRI version to connect RabbitMQ broker on different machine

### ISSUE THREAD

**Issue by marktwtn** [DLTcollab/general#246]
As the implementation of https://github.com/DLTcollab/dcurl/issues/220 and https://github.com/DLTcollab/iri/pull/7, the new IRI can assign the RabbitMQ broker hostname and connect.

All the IRI node should be updated to accelerate PoW with remote FPGA boards through the RabbitMQ broker.

**Comment by marktwtn** [comment]
After I update the release of **IRI** `v1.8.4-COACH`, it can be updated with **Ansible Playbook**.

For assigning the RabbitMQ broker hostname or IP address, add the `--broker-host` option:
`java -jar XXX.jar --pearldiver-exlib dcurl --broker-host <hostname or IP address>`

**Comment by marktwtn** [comment]
@yillkid @ender503 The **IRI** release has been updated.

**Comment by ender503** [comment]
We delay the new version `v1.8.4-COACH` deployment, because we discover a RocksDB crashed issue when stopping the IRI service.

The issue occurred on this new version `v1.8.4-COACH` and previous version `v1.8.4-COACH-REMOTE`.

**Comment by marktwtn** [comment]
The original **iotaledger/iri** `v1.8.4-RELEASE` uses **RocksDB** version `5.17.2`,
and the **DLTcollab/iri** `v1.8.4-COACH` uses **RocksDB** version `5.18.3`.

It turns out that even if we use the **RocksDB** version `5.17.2`, the issue is still existed.

**Comment by marktwtn** [comment]
I used the **iotaledger/iri** `v1.8.4-RELEASE` and it also has a crashed issue when stopping the **IRI** service.
It is recorded as a bug on https://github.com/iotaledger/iri/issues/1742.

I think we should update the IRI and ignore this problem since it is caused by the original **IRI** source code.
@yillkid and @ender503 you can move on to the update.

**Comment by ender503** [comment]
Thanks @marktwtn, we already upgrade all IRI to this `v1.8.4-RELEASE`, the node11 IRI is connected to the RabbitMQ broker successfully, we can find the connection between node11 IRI and broker on Grafana.
