### ISSUE TITLE
Incorrect bundle hash when send transaction on node11

### ISSUE THREAD

**Issue by yillkid** [DLTcollab/general#257]
## Description
Incorrect bundle hash return when send transaction on node11.

#### Request code (node11) :

```
import json
from iota import Iota, ProposedTransaction, Address, TryteString, Tag, Transaction, ProposedBundle, Hash
from iota.trits import trits_from_int
NODE_URL = "http://node.deviceproof.org:14265"
SEED = "RBYYYKDIUDXV9Z9FQPFJSA9QQIGFZASUHE9MHSDPPXYR9ULXZWYNQSOOYHOXSNXEORWGRIQXXINRHKTCU"

receiver_address = "KWRKDYOGXWUCALWLIQMANKCPEQZUULSAXIDDHD9CYWJYBN9ERFBNJRSABWDLFZIPVPZIMMRQHHPIZCM9Z"
txn_tag = "TXNTAGS"
message = {"key":"values"}
value = 0

# Iota instance
api = Iota(NODE_URL, SEED)

# Txn description
txn = ProposedTransaction(
    address = Address(receiver_address),
    message = TryteString.from_string(json.dumps(message)),
    tag = Tag(txn_tag),
    value = value,
    )

# Send transaction
prepared_transferes = []
bundle = ""
prepared_transferes.append(txn)
try:
    bundle = api.send_transfer(
        depth = 3,
        transfers = prepared_transferes,
        min_weight_magnitude = 14
    )
except Exception as e:
    print(e)

print(bundle['bundle'].hash)
```

#### Response:
- [D9RDYGVFOHKZYFXSNPMWXQLXHTPSRFWHOVHPY9AGHHMHYOYEQY9FCHAEWKIATLRZUQBLCONNIIVLZ9999](https://thetangle.org/transaction/D9RDYGVFOHKZYFXSNPMWXQLXHTPSRFWHOVHPY9AGHHMHYOYEQY9FCHAEWKIATLRZUQBLCONNIIVLZ9999)

#### Request code (public node) :

```
import json
from iota import Iota, ProposedTransaction, Address, TryteString, Tag, Transaction, ProposedBundle, Hash
from iota.trits import trits_from_int
NODE_URL = "https://piota-node.com:443"
SEED = "RBYYYKDIUDXV9Z9FQPFJSA9QQIGFZASUHE9MHSDPPXYR9ULXZWYNQSOOYHOXSNXEORWGRIQXXINRHKTCU"

receiver_address = "KWRKDYOGXWUCALWLIQMANKCPEQZUULSAXIDDHD9CYWJYBN9ERFBNJRSABWDLFZIPVPZIMMRQHHPIZCM9Z"
txn_tag = "TXNTAGS"
message = {"key":"values"}
value = 0

# Iota instance
api = Iota(NODE_URL, SEED)

# Txn description
txn = ProposedTransaction(
    address = Address(receiver_address),
    message = TryteString.from_string(json.dumps(message)),
    tag = Tag(txn_tag),
    value = value,
    )

# Send transaction
prepared_transferes = []
bundle = ""
prepared_transferes.append(txn)
try:
    bundle = api.send_transfer(
        depth = 3,
        transfers = prepared_transferes,
        min_weight_magnitude = 14
    )
except Exception as e:
    print(e)

print(bundle['bundle'].hash)
```

#### Response:
- [SXBJRSDEIAKDBYIBXXEENUKVWOBQEYPDRSRMJ9F9FFTSLGXBUQVMZEEGIIALSHNZEFOWQJWPVTTB99999](https://thetangle.org/transaction/SXBJRSDEIAKDBYIBXXEENUKVWOBQEYPDRSRMJ9F9FFTSLGXBUQVMZEEGIIALSHNZEFOWQJWPVTTB99999)

**Comment by yillkid** [comment]
This issue (node11 only) report from community frequently, but the problem seems be solved after I restart the IRI service. Write a simple test as below:
```
WXPT9ECGF9SKDQDDWFHQVYUESC9JINAEOJIPKDR9TNEZBLCKWZGQAFTDIKZPPNIEGN9CGQLDUOXHCWS9C
QRUUOHHSYBNBAAJAGDIHEOGG99JKGECKURJGDCEUDXLKVVHXFDFZ9LA9YVOAZWNGCNZLIJYJA9SRKEYTD
HQAIJDFFJEFGLLHBLBVSNUQFOJLRGZGSJHHKCHFPLBFFSVCODHWHRHVW9IUPVHLITSAL9QJGEKWYFWQS9
MREYXYXZIFHTAXKWNERCOHCIBZEBNLTEKAZINWOGZYIIWLTJVOYDN9ZQKDKJJUEORFFHLFQGIXIQLKGLX
XKJCHFLCCEPVCQZDZGACRPRIUPJBBSXIKLYYKJABV9CYWIPJROXOFVVRVHRDZHOFKYUDCU9VQERBECGHA
QELTLHFTUGNBCE9REFKADH9GNB9CPLAXDDPWLGAASJCZKBVUVGEQZYAUZ9DDCZXISQCJJAIWAHGJUOALZ
ZNACFYPOHDJ9CBCYJSDWLIEOCPRTARDPXPQQIGOGJCIGJHZCDYIJBZREJSTIDDYALTCAGZVEXZPLDJ9ZX
GFQGY9ZLLWVYRZUPXHTCLUEHSHLEXFRXAZRXCKWESH9UXCAJTKWCAKFGC9CCJVQBHRNONCXHHVFGGJLOY
OOX9BTPKBUIQVZFCKKXYTDIWGWD9IIGYZBURFPOHVQGIRPZWHAGR9EUUTSF9KVYJDT99RWTZBCIERFIZD
ZHJJVSZXATCCSXKCWCWPDAQYHKFWCZJQUGJGV9ZHYZNFOZOZBQLUBIRANZL9YVGNCLEGXKRGSXINVLHFY
```

Still can not find the root cause, and I will close this issue.
I will copy the IRI binary and mainnetdb folder to the other VM for tracing this issue occur again.

**Comment by jserv** [comment]
If you are going to close an issue, you must explain and analyze.

**Comment by yillkid** [comment]
This [example code](https://github.com/yillkid/iota-examples/blob/master/sendTransfer.py) will call the IOTA official API [send_transfer](https://github.com/iotaledger/iota.py/blob/master/examples/send_transfer.py) and print the return value (bundle hash value). For example, the message field of expect transaction will like : [LCLKGDYNNXYXBHSA9KFEGREIILAIIWKNJERFRXZKBSVMUDNQYGRZZWIKUSVJHPSXBVJP9VNSRZHWA9999](https://thetangle.org/transaction/LCLKGDYNNXYXBHSA9KFEGREIILAIIWKNJERFRXZKBSVMUDNQYGRZZWIKUSVJHPSXBVJP9VNSRZHWA9999). But in this case we got the encoded message (the transaction hash: [D9RDYGVFOHKZYFXSNPMWXQLXHTPSRFWHOVHPY9AGHHMHYOYEQY9FCHAEWKIATLRZUQBLCONNIIVLZ9999](https://thetangle.org/transaction/D9RDYGVFOHKZYFXSNPMWXQLXHTPSRFWHOVHPY9AGHHMHYOYEQY9FCHAEWKIAThe issue will be fixedTLRZUQBLCONNIIVLZ9999), ans this transaction not issued from our seed.

1. After we check the timestamp and all hash value (bundle and transaction hash), the return value will be an unrelated transaction in Tangle.

2. No error message on IRI deamon log: [Download](https://drive.google.com/file/d/1TeEfrrTmQktFlo6nAYE00JDlACrnOAXO/view?usp=sharing)

3. The issue will be fixed if change the [URL of full-node](https://github.com/yillkid/iota-examples/blob/master/config.py#L1) to the public node (https://piota-node.com:443), it's a full-node issue.

4. This issue can not be reproduce after I restart the IRI daemon.

5. I will close this issue, but if this issue occur again, I will copy the IRI launch file and mainnetdb folder to new a VM for tracing it.
