### ISSUE TITLE
Upgrade to IRI 1.8.6 and finalize IRI support

### ISSUE THREAD

**Issue by jserv** [DLTcollab/general#258]
[IRI-1.8.6](https://github.com/iotaledger/iri/releases) is known to be the last IRI release supported by IOTA Foundation. Here are the expected results:
1. Rebase iri-1.8.6 for our customized changes.
2. We run single IRI instance in NCKU and NCTU.
3. Deploy HORNET in virtualized environments.

NOTE:
* Due to a change to local snapshots format, we have to convert them using the instructions found here https://docs.iota.org/docs/iri/1.0/tutorials/update-iri. Or download a fresh one.
* Updated RocksDB to 6.2.2

**Comment by marktwtn** [comment]
The [v1.8.6-COACH](https://github.com/DLTcollab/iri/releases/tag/v1.8.6-COACH) has been released.

Note:
- The redundant commits are removed.
- The updated RocksDB is version `6.3.6`.
- The RocksDB related commits are removed as well, since we do not have to use our RocksDB anymore. If it is required in the future, I will add the corresponding commit for using our RocksDB.

@yillkid you can prepare for the node update.

**Comment by yillkid** [comment]
TODOs :
- [ ] Upgrade Node1
- [ ] Upgrade Node10
- [ ] Upgrade Node11

**Comment by jserv** [comment]
What's the progress on node10 and node11?

**Comment by yillkid** [comment]
> What's the progress on node10 and node11?

Node10 will replace the `mainnetdb` of `node11`, blocked by #261 .
Node11 will upgrade to 1.8.6 after `node10`

**Comment by yillkid** [comment]
Switch `node10` from permanode to full-node due to #261.

**Comment by yillkid** [comment]
node11:

```json
{
    "appName": "IRI",
    "appVersion": "1.8.6-COACH",
    "coordinatorAddress": "EQSAUZXULTTYZCLNJNTXQTQHOMOFZERHTCGTXOLTVAHKSA9OGAZDEKECURBRIXIJWNPFCQIOVFVVXJVD9",
    "dbSizeInBytes": 407153831065,
    "duration": 0,
    "features": [
        "dnsRefresher",
        "zeroMessageQueue",
        "RemotePOW",
        "WereAddressesSpentFrom"
    ],
    "jreAvailableProcessors": 48,
    "jreFreeMemory": 647589192,
    "jreMaxMemory": 3937402880,
    "jreTotalMemory": 1282932736,
    "jreVersion": "1.8.0_252",
    "lastSnapshottedMilestoneIndex": 1467445,
    "latestMilestone": "FJPIFMQLODJRKDHRMYPJLYGYICH9G9EOLIAGRBDXYXHQZJRZFOBTWXUBQGWWACYPSFQXTGYQYWQYA9999",
    "latestMilestoneIndex": 1467646,
    "latestSolidSubtangleMilestone": "FJPIFMQLODJRKDHRMYPJLYGYICH9G9EOLIAGRBDXYXHQZJRZFOBTWXUBQGWWACYPSFQXTGYQYWQYA9999",
    "latestSolidSubtangleMilestoneIndex": 1467646,
    "milestoneStartIndex": 1050001,
    "neighbors": 5,
    "packetsQueueSize": 0,
    "time": 1594001631594,
    "tips": 5442,
    "transactionsToRequest": 0
}
```
