### ISSUE TITLE
Docs: difference of consistency algorithm, whitepaper and IRI

### ISSUE THREAD

**Issue by yillkid** [DLTcollab/general#32]
In gitlab by @root on Dec 11, 2017, 21:22

Expected goals:

1. find the limit of consensus algorithms;
2. find how to attack tangle network;
3. find how to defend attacks mentioned in Tangle whitepaper; 

Reference:
https://hackmd.io/c/HyQrzrV0Z/https%3A%2F%2Fwusyong.gitbooks.io%2Fiota-guidebook%2F

**Comment by yillkid** [comment]
In gitlab by @root on Dec 23, 2017, 19:16

*Created by: proof.K*

Add node state case when node receives new transaction.

**Comment by yillkid** [comment]
In gitlab by @root on Dec 27, 2017, 13:47

*Created by: proof.K*

Finish node state case when node receives new transaction and the case about weight growth.

**Comment by yillkid** [comment]
In gitlab by @proof.K on Jan 22, 2018, 16:14

changed title from **{-共識演算法,白皮書與IRI的差異-}** to **{+The difference of Consistent Algorithm , While Paper and IOTA Reference Implementation+}**

**Comment by yillkid** [comment]
In gitlab by @proof.K on Jan 22, 2018, 16:14

changed the description

**Comment by yillkid** [comment]
In gitlab by @proof.K on Jan 22, 2018, 16:15

changed title from **The difference of Consistent Algorithm , Whi{-l-}e Paper and IOTA Reference Implementation** to **The difference of Consistent Algorithm , Whi{+t+}e Paper and IOTA Reference Implementation**

**Comment by yillkid** [comment]
In gitlab by @proof.K on Jan 22, 2018, 16:17

changed the description

**Comment by yillkid** [comment]
In gitlab by @proof.K on Jan 22, 2018, 16:17

changed the description

**Comment by yillkid** [comment]
In gitlab by @proof.K on Jan 22, 2018, 16:18

add how to solve Byzantine Generals Problem

**Comment by yillkid** [comment]
In gitlab by @proof.K on Jan 24, 2018, 20:38

add tittle "lazy tip"

https://hackmd.io/s/HyQrzrV0Z#lazy-tip

**Comment by yillkid** [comment]
In gitlab by @proof.K on Jan 24, 2018, 20:40

add tittle "Transaction's life cycle"

https://hackmd.io/s/HyQrzrV0Z#一筆交易在node的生命週期

**Comment by yillkid** [comment]
In gitlab by @proof.K on Jan 24, 2018, 20:43

add the probability analysis　of successful attack White Paper talks about.


https://hackmd.io/s/HyQrzrV0Z#白皮書攻擊成功機率說明

**Comment by yillkid** [comment]
In gitlab by @proof.K on Jan 24, 2018, 21:17

update content in hypothesis of Consistent Algorithm

https://hackmd.io/s/HyQrzrV0Z#我對共識演算法的看法與假設

**Comment by yillkid** [comment]
In gitlab by @proof.K on Jan 25, 2018, 16:23

add URL

https://hackmd.io/s/SkPJjZwSG

https://hackmd.io/s/rJsc2bDBz


https://hackmd.io/s/rkuRpbPHf

**Comment by yillkid** [comment]
In gitlab by @jserv on Feb 2, 2018, 18:14

assigned to @proof.K

**Comment by yillkid** [comment]
In gitlab by @proof.K on Feb 3, 2018, 18:00

finish case about "double spend".

https://hackmd.io/s/HyQrzrV0Z#有衝突交易的DAG

**Comment by yillkid** [comment]
In gitlab by @proof.K on Feb 11, 2018, 16:09

modify split attack description. 

https://hackmd.io/s/SkPJjZwSG#分裂攻擊

**Comment by yillkid** [comment]
In gitlab by @proof.K on Feb 13, 2018, 21:01

give a example to analyze　transaction cumulative weight.


[一筆交易最終的權重增長](https://hackmd.io/s/Bk1vw3B8z)

**Comment by yillkid** [comment]
In gitlab by @proof.K on Feb 25, 2018, 17:15

Build book model.

[共識演算法,白皮書與IRI的差異](https://hackmd.io/c/HyQrzrV0Z/https%3A%2F%2Fgithub.com%2FNONEYMOUS%2FIOTA-CONSENSUS-PRESENTATION)

**Comment by yillkid** [comment]
In gitlab by @proof.K on Feb 27, 2018, 17:57

add introduction of IOTA system. 



[IOTA系統架構簡介](https://hackmd.io/c/HyQrzrV0Z/https%3A%2F%2Fhackmd.io%2Fs%2FH1BCR6JuM)

**Comment by yillkid** [comment]
In gitlab by @proof.K on Mar 1, 2018, 13:13

modify introduction of IOTA system.

[IOTA系統架構簡介](https://hackmd.io/s/H1BCR6JuM)

**Comment by yillkid** [comment]
In gitlab by @proof.K on Mar 1, 2018, 19:17

add tittle "how to find bad neighbor node".



[node如何發現不合作的鄰居node](https://hackmd.io/s/Hk5PpxldG#node如何發現不合作的鄰居node)

**Comment by yillkid** [comment]
In gitlab by @proof.K on Mar 2, 2018, 17:25

add more analysis of checking transaction.


[白皮書提到的交易選取算法問題](https://hackmd.io/s/rkZAX1xuf#白皮書提到的交易選取算法問題)

**Comment by yillkid** [comment]
In gitlab by @proof.K on Mar 5, 2018, 16:44

add more analysis of non-cooperation neighbor node.



[與鄰居node保持連線的條件](https://hackmd.io/s/Hk5PpxldG#與鄰居node保持連線的條件)

**Comment by yillkid** [comment]
In gitlab by @proof.K on Mar 6, 2018, 14:59

add more analysis of DOS.


[Dos](https://hackmd.io/s/Hk5PpxldG#兩個都-confirmation)

**Comment by yillkid** [comment]
In gitlab by @proof.K on Mar 6, 2018, 15:44

discuss different methods to deal with non-cooperation neighbor node.


[知道不合作鄰居node後的應對](https://hackmd.io/s/Hk5PpxldG#知道不合作鄰居node後的應對)

**Comment by yillkid** [comment]
In gitlab by @proof.K on Mar 16, 2018, 19:22

add "Confirmation" chapter.


[確認](https://hackmd.io/s/HyYil3DYz)

**Comment by yillkid** [comment]
In gitlab by @jserv on Mar 16, 2018, 23:39

changed title from **{-The difference of Consistent Algorithm , White Paper and IOTA Reference Implementation-}** to **{+Docs: difference of consistency algorithm, whitepaper and IRI+}**

**Comment by yillkid** [comment]
In gitlab by @proof.K on Mar 20, 2018, 21:16

add analysis of transaction confirmation.


[DAG 加入一筆交易對確認度的影響](https://hackmd.io/s/HyYil3DYz#DAG-%E5%8A%A0%E5%85%A5%E4%B8%80%E7%AD%86%E4%BA%A4%E6%98%93%E5%B0%8D%E7%A2%BA%E8%AA%8D%E5%BA%A6%E7%9A%84%E5%BD%B1%E9%9F%BF)

**Comment by yillkid** [comment]
In gitlab by @proof.K on Mar 26, 2018, 15:46

add more analysis of transaction confirmation.


[有新的 tip , 對其他 tip 貢獻確認度的影響](https://hackmd.io/s/HyYil3DYz#%E6%9C%89%E6%96%B0%E7%9A%84-tip--%E5%B0%8D%E5%85%B6%E4%BB%96-tip-%E8%B2%A2%E7%8D%BB%E7%A2%BA%E8%AA%8D%E5%BA%A6%E7%9A%84%E5%BD%B1%E9%9F%BF)

[有衝突交易的 DAG , 交易如何指向](https://hackmd.io/s/HyYil3DYz#%E6%9C%89%E8%A1%9D%E7%AA%81%E4%BA%A4%E6%98%93%E7%9A%84-DAG--%E4%BA%A4%E6%98%93%E5%A6%82%E4%BD%95%E6%8C%87%E5%90%91)

**Comment by yillkid** [comment]
In gitlab by @proof.K on Mar 27, 2018, 15:23

add how to calculate confirmation.


[一種確認度的算法](https://hackmd.io/s/HyYil3DYz#%E4%B8%80%E7%A8%AE%E7%A2%BA%E8%AA%8D%E5%BA%A6%E7%9A%84%E7%AE%97%E6%B3%95)

**Comment by yillkid** [comment]
In gitlab by @proof.K on Apr 1, 2018, 16:34

changed the description

**Comment by yillkid** [comment]
In gitlab by @proof.K on Apr 1, 2018, 16:38

add an example.



[確認度例子](https://hackmd.io/s/HyYil3DYz#%E4%B8%80%E7%A8%AE%E7%A2%BA%E8%AA%8D%E5%BA%A6%E7%9A%84%E7%AE%97%E6%B3%95)

**Comment by yillkid** [comment]
In gitlab by @proof.K on Apr 3, 2018, 17:35

More analysis of double-spending.


[對增加衝突交易確認度的交易數量估計](https://hackmd.io/s/HyYil3DYz#%E5%B0%8D%E5%A2%9E%E5%8A%A0%E8%A1%9D%E7%AA%81%E4%BA%A4%E6%98%93%E7%A2%BA%E8%AA%8D%E5%BA%A6%E7%9A%84%E4%BA%A4%E6%98%93%E6%95%B8%E9%87%8F%E4%BC%B0%E8%A8%88)

**Comment by yillkid** [comment]
In gitlab by @proof.K on Apr 10, 2018, 20:43

Describe property of transaction confirmation.


[DAG 上確認度的偏序關係](https://hackmd.io/s/HyYil3DYz#DAG-%E4%B8%8A%E7%A2%BA%E8%AA%8D%E5%BA%A6%E7%9A%84%E5%81%8F%E5%BA%8F%E9%97%9C%E4%BF%82)

**Comment by yillkid** [comment]
In gitlab by @proof.K on Apr 14, 2018, 16:25

More analysis of transaction confirmation growth.

[一筆交易最終的確認度增長](https://hackmd.io/s/Sy9iBlgOM#%E4%B8%80%E7%AD%86%E4%BA%A4%E6%98%93%E6%9C%80%E7%B5%82%E7%9A%84%E7%A2%BA%E8%AA%8D%E5%BA%A6%E5%A2%9E%E9%95%B7)

**Comment by yillkid** [comment]
In gitlab by @proof.K on Apr 19, 2018, 16:33

Analysis of IOTA foundation confirmation confidence.


[基金會的確認度算法](https://hackmd.io/s/HyYil3DYz#%E5%9F%BA%E9%87%91%E6%9C%83%E7%9A%84%E7%A2%BA%E8%AA%8D%E5%BA%A6%E7%AE%97%E6%B3%95)

**Comment by yillkid** [comment]
In gitlab by @proof.K on Apr 24, 2018, 16:35

Problem of approving two conflicting transactions.

[不收同時指向衝突交易的交易](https://hackmd.io/s/Sk6a7rhnf#%E4%B8%8D%E6%94%B6%E5%90%8C%E6%99%82%E6%8C%87%E5%90%91%E8%A1%9D%E7%AA%81%E4%BA%A4%E6%98%93%E7%9A%84%E4%BA%A4%E6%98%93)

**Comment by yillkid** [comment]
In gitlab by @proof.K on May 1, 2018, 16:41

More analysis of IOTA foundation confirmation confidence.

[指向一筆交易的 tip 比例](https://hackmd.io/s/HyYil3DYz#%E6%8C%87%E5%90%91%E4%B8%80%E7%AD%86%E4%BA%A4%E6%98%93%E7%9A%84-tip-%E6%AF%94%E4%BE%8B)

**Comment by yillkid** [comment]
In gitlab by @proof.K on May 8, 2018, 21:01

About confirmation.

[交易如何確認?](https://hackmd.io/s/rkuRpbPHf#%E4%BA%A4%E6%98%93%E5%A6%82%E4%BD%95%E7%A2%BA%E8%AA%8D)

**Comment by yillkid** [comment]
In gitlab by @proof.K on Jun 7, 2018, 15:19

New question about transactions to approve.

[有疑慮的指向](https://hackmd.io/s/r11BMVLxQ#%E6%9C%89%E7%96%91%E6%85%AE%E7%9A%84%E6%8C%87%E5%90%91)

**Comment by yillkid** [comment]
In gitlab by @jserv on Jun 13, 2018, 03:58

changed the description

**Comment by yillkid** [comment]
In gitlab by @jserv on Jun 13, 2018, 04:01

We need verbose tracking for such fundamental tasks. Be transparent when clarifying.

**Comment by KevinKu** [comment]
The topic belongs to IOTA whitepaper.So,I close it.
