### ISSUE TITLE
LASS: Integrate TangleID and manage sensor data

### ISSUE THREAD

**Issue by yillkid** [DLTcollab/general#42]
In gitlab by @twzjwang on Feb 3, 2018, 16:41

# Done
- encoding sensor data
- Python decode function
- integrate TangleID api
- wirelessly updated from Arduino IDE

# Action Items
- verify data correctness

**Comment by yillkid** [comment]
In gitlab by @twzjwang on Feb 10, 2018, 16:39

Fix casting bug.<br />
`difference = (int)(current_value - previous_value)`<br />
should be<br />
`difference = (int)current_value - (int)previous_value`<br />
in Hack4U.<br />

**Comment by yillkid** [comment]
In gitlab by @twzjwang on Feb 10, 2018, 16:47

Modify encoding function<br />
1. avoid a skewed binary tree<br />
2. extend the range of symbols to **+-50** <br />
3. reduce **discard ratio** from 1.5 % to **0.04 %** <br />
4. **compression ratio** is changed from 10.51 % to **12.9 %**

**Comment by yillkid** [comment]
In gitlab by @twzjwang on Feb 10, 2018, 16:50

HackMD : https://hackmd.io/s/SJnlK_8yM#Details

**Comment by yillkid** [comment]
In gitlab by @jserv on Mar 16, 2018, 23:18

changed title from **{-Integrate LASS with TangleID-}** to **{+LASS: Integrate TangleID and manage sensor data+}**

**Comment by yillkid** [comment]
In gitlab by @twzjwang on Apr 24, 2018, 11:23

[(IOTA 版本) 空氣盒子教學](https://hackmd.io/s/H1HxM-2hz)

**Comment by yillkid** [comment]
In gitlab by @twzjwang on May 23, 2018, 15:00

list of UUIDs 
https://thetangle.org/tag/LASSUUIDLISTC

**Comment by yillkid** [comment]
In gitlab by @jserv on Jun 6, 2018, 08:24

[RuuviTag firmware](https://github.com/ruuvi/ruuvitag_fw) comes with statically-linked MAM library compiled for Arm Cortex-M. It would be great if we can adopt the existing work for Airbox.

Check the directory `ruuvi_examples/test_drivers` in repository [RuuviTag firmware](https://github.com/ruuvi/ruuvitag_fw):
* File `libiota_mam_bindings.a` is exactly static library compiled from Rust.
* File `mam.[ch]`

NOTE: the library was tested under Nornic nRF52, consisting of Cortex-M4F processor.

**Comment by twzjwang** [comment]
"ERROR opening socket" after 15 records
```
epoch = 1529486033 | s_d0 = 2 | s_d1 = 2 | s_t0 = 29 | s_h0 = 46
epoch = 1529486093 | s_d0 = 2 | s_d1 = 2 | s_t0 = 29 | s_h0 = 46
epoch = 1529486153 | s_d0 = 2 | s_d1 = 3 | s_t0 = 29 | s_h0 = 47
Connected to wifi
Starting connection...
ERROR opening socket
Connected failed
```

**Comment by twzjwang** [comment]
Add an experiment for compression ratio  

| | compressed / uncompressed size | uncompressed / compressed size |
| -- | -- | -- |
| Theoretical value | 12.94 % | 7.73 |
| Experimental value | 9.984 % | 10.02 |

![figure_1](https://user-images.githubusercontent.com/11258501/42411730-99583886-8233-11e8-9ca5-722968798b69.png)

**Comment by jserv** [comment]
Avoid using the same color while plotting histogram, otherwise we can not distinguish.

**Comment by jserv** [comment]
Firmware and its documentation are landed: [airbox-with-iota](https://github.com/DLTcollab/airbox-with-iota).
