### ISSUE TITLE
Docs: Translate Oyster Protocol whitepaper

### ISSUE THREAD

**Issue by yillkid** [DLTcollab/general#50]
In gitlab by @root on Feb 22, 2018, 21:28

[Oyster](https://oysterprotocol.com) is a open source project provide a service to decentralize attaching the website content into IOTA Tangle and an aware mechanism for POW and broker Nodes. I plan to translate the Oyster whitepaper and thinking about any improvement for TangleID.

Reference:
* [Oyster whitepaper 0.7b](https://oysterprotocol.com/assets/pdf/OysterWhitepaper.pdf)
* [Oyster whitepaper 0.7b (中譯)](https://hackmd.io/s/B1RjD0sDz)
* [Oysterprotocol GitHub page](https://github.com/oysterprotocol)

Action items:
* Oyster Protocol whitepaper transaction
* Mechanism of how Oyster file storage on the Tangle

**Comment by yillkid** [comment]
In gitlab by @jserv on Mar 16, 2018, 23:28

changed title from **Translate Oyster whitepaper** to **{+Docs: +}Translate Oyster whitepaper**

**Comment by yillkid** [comment]
In gitlab by @jserv on May 10, 2018, 20:30

assigned to @twzjwang

**Comment by yillkid** [comment]
In gitlab by @jserv on May 10, 2018, 20:32

Assign to @twzjwang. We don't have to translate the whole whitepaper. Instead, only summarize how Oyster works in existing HackMD page initiated by @root.

**Comment by yillkid** [comment]
In gitlab by @twzjwang on May 16, 2018, 16:11

[Oyster 筆記](https://hackmd.io/s/B1V2oZt0z)

**Comment by yillkid** [comment]
In gitlab by @twzjwang on May 16, 2018, 16:12

changed the description

**Comment by yillkid** [comment]
In gitlab by @twzjwang on May 16, 2018, 16:12

created branch [`35-docs-translate-oyster-whitepaper`](http://node0.puyuma.org:10081/root/general/compare/master...35-docs-translate-oyster-whitepaper)

**Comment by yillkid** [comment]
In gitlab by @twzjwang on May 16, 2018, 16:12

mentioned in merge request !1

**Comment by yillkid** [comment]
In gitlab by @jserv on May 16, 2018, 16:12

changed title from **Docs: Translate Oyster whitepaper** to **Docs: Translate Oyster {+Protocol +}whitepaper**

**Comment by yillkid** [comment]
In gitlab by @jserv on May 16, 2018, 16:12

changed the description

**Comment by yillkid** [comment]
In gitlab by @twzjwang on May 19, 2018, 23:57

add "Burying Pearls with Broker Nodes"  
[由經紀人節點埋藏 Pearls](https://hackmd.io/s/B1V2oZt0z#%E7%94%B1%E7%B6%93%E7%B4%80%E4%BA%BA%E7%AF%80%E9%BB%9E%E5%9F%8B%E8%97%8F-Pearls)

**Comment by yillkid** [comment]
In gitlab by @twzjwang on May 22, 2018, 12:50

add "Treasure Hunting for Oyster Pearls"  
[Oyster Pearls 尋寶](https://hackmd.io/s/B1V2oZt0z#Oyster-Pearls-%E5%B0%8B%E5%AF%B6)

**Comment by yillkid** [comment]
In gitlab by @twzjwang on May 26, 2018, 15:49

add "Web Node and Broker Node Collaboration"  
[Web 節點和經紀人節點的協作](https://hackmd.io/s/B1V2oZt0z#Web-%E7%AF%80%E9%BB%9E%E5%92%8C%E7%B6%93%E7%B4%80%E4%BA%BA%E7%AF%80%E9%BB%9E%E7%9A%84%E5%8D%94%E4%BD%9C)

**Comment by twzjwang** [comment]
Add [內容消費權利](https://hackmd.io/s/B1V2oZt0z#%E5%85%A7%E5%AE%B9%E6%B6%88%E8%B2%BB%E6%AC%8A%E5%88%A9)

**Comment by jserv** [comment]
[Simplified Chinese translation](https://oysterprotocol.com/assets/pdf/OysterWhitepaper_CN.pdf) is available on Oyster Protocol website.

**Comment by jserv** [comment]
No further upstream changes. DONE.

**Comment by jserv** [comment]
Oyster Protocol Revamps as Opacity by the end of 2018.
