### ISSUE TITLE
Tangle timestamping study and evaluation

### ISSUE THREAD

**Issue by yillkid** [DLTcollab/general#60]
In gitlab by @proof.K on Mar 14, 2018, 16:56

[Equilibria in the Tangle](https://arxiv.org/pdf/1712.05385.pdf)

**Comment by wusyong** [comment]
There an ixi module for ict to implement the method described in "[On the timestamps in the tangle](https://assets.ctfassets.net/r1dr6vzfxhev/4XgiKaTkUgEyW8O8qGg6wm/32f3a7c28022e35e4d5d0e858c0973a9/On_the_timestamps_in_the_tangle_-_20182502.pdf)
":
https://github.com/iotaledger/timestamping.ixi
