### ISSUE TITLE
Base: construct private IOTA testnet for evaluation and Demo Kit purpose

### ISSUE THREAD

**Issue by yillkid** [DLTcollab/general#76]
Potential partners or collaborators would like to evaluate Tangle-based services such as `iota-swarm-node` or `TangleID`. However, uncertainty resulting from mainnet prevents people from being confident to move forward. Instead, we expect to construct effective private IOTA testnet for the sake of closed-environment evaluation. Also, it is crucial for Demo Kit.

Expected output:
* Follow the steps described in [Kiri: Private IOTA testnet in Kura](https://trustingiot.com/2018/04/02/kiri-private-iota-testnet-in-kura/), [Increasing the autonomy of Kiri](https://trustingiot.com/2018/04/20/increasing-the-autonomy-of-kiri/), and [run/kiri/run: Increasing the speed of Kiri](https://trustingiot.com/2018/04/24/run-kiri-run-increasing-the-speed-of-kiri/)
* Enable private IOTA testnet on ARM64 instances.

**Comment by yillkid** [comment]
Since we got new Intel Xeon E5 class server online, we would construct private testnet on `node10` host.

**Comment by jserv** [comment]
It is not feasible to have Aarch64-based full-functioned nodes at the moment.
