### ISSUE TITLE
Docs: Illustrate how tip selection algorithm works

### ISSUE THREAD

**Issue by jserv** [DLTcollab/general#80]
IRI version `1.5.0` comes with a complete rewrite of the tip selection algorithm. There are several informative entries:
* [The Tangle: an Illustrated Introduction](https://blog.iota.org/the-tangle-an-illustrated-introduction-4d5eae6fe8d4)
* [TipSelection Algorithm Documentation](https://hackmd.io/s/Skow-8Hb7)

Wayne translated [TipSelection Algorithm Documentation](https://hackmd.io/s/Skow-8Hb7) into Traditional Chinese, and it would be great if we can experiment in real-world showcase.

Expected output:
1. Explain how tip selection algorithm works in regular meetings;
2. Use visualization tools such as #47 to illustrate the internals;
3. Introspect recent TPS/CTPS behavior;

**Comment by KevinKu** [comment]
Write a document to explain.

[1.5.0 TipSelection Algorithm](https://hackmd.io/s/HyddgJGGX)
