### ISSUE TITLE
Base: Improve CTPS and reduce confirmation time

### ISSUE THREAD

**Issue by KevinKu** [DLTcollab/general#81]
Merge [#77](https://github.com/DLTcollab/general/issues/77) and [#72](https://github.com/DLTcollab/general/issues/72)

Doc:[提高ctps實驗](https://hackmd.io/s/BkHdrVeRM)

**Comment by KevinKu** [comment]
Describe thinking about second goal.

[縮短交易確認的時間](https://hackmd.io/s/BkHdrVeRM#%E7%B8%AE%E7%9F%AD%E4%BA%A4%E6%98%93%E7%A2%BA%E8%AA%8D%E7%9A%84%E6%99%82%E9%96%93)

**Comment by KevinKu** [comment]
problem:[有疑慮的指向](https://hackmd.io/s/r11BMVLxQ#%E6%9C%89%E7%96%91%E6%85%AE%E7%9A%84%E6%8C%87%E5%90%91)

Add solution:
[處理辦法
](https://hackmd.io/s/r11BMVLxQ#%E8%99%95%E7%90%86%E8%BE%A6%E6%B3%95)

**Comment by KevinKu** [comment]
Spammer test.

[最近的CTPS](https://hackmd.io/s/BkHdrVeRM#%E6%9C%80%E8%BF%91%E7%9A%84CTPS)

**Comment by jserv** [comment]
Let's close this and split into several executive action items.
