### ISSUE TITLE
Deploy tools to monitor and visualize Tangle real-time behaviour

### ISSUE THREAD

**Issue by ender503** [DLTcollab/general#83]
[Prometheus](https://prometheus.io/) is a great monitoring tool, that can help with the following: 
 - Gather the matrix data from nodes.
 - Provide the API to query the matrix data.
 - Great visualization tool with Grafana.
 - Make notification when service is down.

With the [iota-prom-exporter](https://github.com/crholliday/iota-prom-exporter), we can gather following information from IOTA node.
 - TPS, CTPS.
 - Average confirmation time, confirmation rate.
 - Neighbors status.

I make a demo site to monitor the DeviceProof with Prometheus and Grafana
site: http://node0.puyuma.org:9300/d/000000004/node1-testnet?refresh=30s&orgId=1
username: admin
password: foobar

Expected output:
 - Deploy the `iota-prom-exporter` to our IOTA nodes to gather nodes information.
 - Make notification to slack channel when nodes are offline.
 - Make the dashboard to monitor the IOTA nodes.

### Screenshot

![top of dashboard](https://github.com/crholliday/iota-prom-exporter/raw/master/images/top_new.png)

#### Market pricing and Stresstest

![top of dashboard](https://raw.githubusercontent.com/crholliday/iota-prom-exporter/master/images/zmq.png)

#### Neighbors

![top of dashboard](https://github.com/crholliday/iota-prom-exporter/raw/master/images/neighbors.png)

**Comment by jserv** [comment]
You shall mention "expected output" in this task, otherwise we could not realize the impact and its importance.

**Comment by KevinKu** [comment]
I think testing API in higher TPS(like TPS > 20 or some number) is needed.
Logging API response can help us know IRI performance in high TPS.

**Comment by jserv** [comment]
Function verified. Let's split into dedicated tickets.
