### ISSUE TITLE
Base: problem about side tangle

### ISSUE THREAD

**Issue by KevinKu** [DLTcollab/general#85]
IRI issue:[846](https://github.com/iotaledger/iri/issues/846)

First problem : getTransactionsToApprove freezes
Second problem : ctps down

**Comment by jserv** [comment]
@KevinKu, summarize IRI discussions as well.

**Comment by KevinKu** [comment]
[Doc](https://hackmd.io/s/Hye2qhamm)

**Comment by KevinKu** [comment]
[最近 mainnet 的 Tangle](https://hackmd.io/s/Hye2qhamm#%E6%9C%80%E8%BF%91-mainnet-%E7%9A%84-Tangle)

**Comment by jserv** [comment]
You shall write down some words here in order to improve traceability.

**Comment by KevinKu** [comment]
Solution about getTransactionsToApprove freezes.

[IF solution](https://hackmd.io/s/Hye2qhamm#getTransactionsToApprove)

**Comment by KevinKu** [comment]
Describe IRI 1.5.2 change about  issue 846.

[IRI 1.5.2](https://hackmd.io/s/Hye2qhamm#IRI-152)

**Comment by jserv** [comment]
Still valid?

**Comment by KevinKu** [comment]
I don't know if it is valid at IRI 1.5.5 or later.
But it can be tested by [DOS-attack-with-FPGA-accelerator](https://github.com/DLTcollab/DOS-attack-with-FPGA-accelerator).
I think the issue can be closed and move it to DOS-attack-with-FPGA-accelerator's issue.
