### ISSUE TITLE
Base: IRI with local snapshot (coordinator exists)

### ISSUE THREAD

**Issue by KevinKu** [DLTcollab/general#86]
From [doc](https://hackmd.io/s/rJN51lGXQ) , we know transaction referenced by milestone is confirmed.
So , I think IRI can delete these transaction and compute these addresses balance.

I think it has other problems.

Let's discuss it.

**Comment by KevinKu** [comment]
Describe how to do local snapshot and related problem.

[Doc](https://hackmd.io/s/BJoJSjNV7)

**Comment by KevinKu** [comment]
Modify problem description.

[驗證到被 local snapshot 的交易](https://hackmd.io/s/BJoJSjNV7#%E9%A9%97%E8%AD%89%E5%88%B0%E8%A2%AB-local-snapshot-%E7%9A%84%E4%BA%A4%E6%98%93)

**Comment by KevinKu** [comment]
Problem about synchronizing ledger.

[node 同步](https://hackmd.io/s/BJoJSjNV7#node-同步)

**Comment by wusyong** [comment]
@jserv IRI with local snapshot is still in RC version. Better wait until full release in case of there may be some issues like recent hot fixes.

**Comment by wusyong** [comment]
[Documentation of local snapshot](https://github.com/jakubcech/documentation/blob/master/LS-preview.MD)

**Comment by KevinKu** [comment]
@wusyong 
Agree.

**Comment by jserv** [comment]
Duplicated with #102
