### ISSUE TITLE
Base: problem about "broadcastTransactions"

### ISSUE THREAD

**Issue by KevinKu** [DLTcollab/general#88]
The command "broadcastTransactions" has a problem.
If node don't limit the command after coordinator doesn't exist.  Then , attacker can use the command to broadcast problematic transaction.
Further , some address balance will be modified.

**Comment by KevinKu** [comment]
add more detail about "broadcastTransactions" problem.

[problem about “broadcastTransactions”](https://hackmd.io/s/rJFnwKLUm)

**Comment by KevinKu** [comment]
add more analysis.

[個人的想法](https://hackmd.io/s/rJFnwKLUm#%E5%80%8B%E4%BA%BA%E7%9A%84%E6%83%B3%E6%B3%95)

**Comment by jserv** [comment]
Still valid for IRI 1.5.5?

**Comment by KevinKu** [comment]
Yes.
Because commands aren't changed.
