### ISSUE TITLE
Load balancer for Tangle-accelerator

### ISSUE THREAD

**Issue by yillkid** [DLTcollab/general#90]
We should deploy a load balancer for `Tangle-accelerator` to dispatch incoming application-aware traffic across multiple targets,  followed by a brief description:

![arc](https://user-images.githubusercontent.com/185872/44885218-38372000-acf2-11e8-94e0-ce3805e47eda.png)

The solution of load balancing is [Nginx](https://www.nginx.com/) [ngx_http_upstream_module](http://nginx.org/en/docs/http/ngx_http_upstream_module.html) that is used to define groups of servers that can be referenced by the proxy_pass, fastcgi_pass, uwsgi_pass, scgi_pass, memcached_pass, and grpc_pass directives.

A detail deploy note can be found via [here](https://hackmd.io/s/S1loLtv4Q).

TODO:

* Deploy plan
* Monitor tool

Done:
* Service log

**Comment by yillkid** [comment]
Service log - https://hackmd.io/bs-DQryNRA2Xv5KxcKGYtg?view#Service-file

**Comment by jserv** [comment]
[iri-lb-haproxy](https://github.com/nuriel77/iri-lb-haproxy) is meant for private IRI nodes cluster.

It is based on Consul and HAproxy, the latter being a robust, feature rich load balancer. In addition to Consul, Consul Template is used to watch services in Consul and update Haproxy.

@yillkid, confirm feasible solutions in advance.

**Comment by yillkid** [comment]
A study note can be found [here](https://hackmd.io/s/B1VnrCj_X)

* DONE
  * Register/Deregister service for IOTA full-node
  * Health check for IOTA full-node
* TODO
  * IOTA API Proxy
  * Prometheus integration
  * Tangle Accelerator extension

**Comment by yillkid** [comment]
#### MAINNET
Load balancing - http://node0.puyuma.org:8002

TESTNET
Load balancing - http://node0.puyuma.org:8000

**Comment by jserv** [comment]
@yillkid, can you transfer this ticket to @jkrvivian ? So that, you can focus on other maintenance issues.

**Comment by jserv** [comment]
In favor of #94
