### ISSUE TITLE
Study powsrv PoWaaS (PoW-as-a-service)

### ISSUE THREAD

**Issue by yillkid** [DLTcollab/general#91]
[Powsrv](https://powsrv.io/) is a PoWaaS (PoW-as-a-service) powered by [pidiver](https://ecosystem.iota.org/projects/iota-pearl-diver-pow-fpga-raspberry-pi) for IOTA wallet, MAM-stream or any IOTA usecase requiring fast transaction turnout. I am studying the implementation and evaluate if it can be a reference for [iota-swarm-node](https://github.com/yillkid/iota-swarm-node) or not. The key points are:

* Performance benchmark test
* The implement of official IOTA library patch
  * The workaround is to override `attachToTangle` API of official IOTA library
  * Think about the better solution?

A detail study note can be found on [here](https://hackmd.io/s/HkRiiUGw7).

**Comment by jserv** [comment]
It is not a feasibly technical thing. Pity.
