### ISSUE TITLE
Base: User authentication for load balancer

### ISSUE THREAD

**Issue by yillkid** [DLTcollab/general#94]
User authentication and access for mobile applications and IoT devices, followed by a brief description:

![arc_auth](https://user-images.githubusercontent.com/185872/45278814-55919880-b501-11e8-91de-131b7599afbc.png)

The auth server provide a login provider authentication token for different applications (mobile or IoT device), the auth seriver collects a user's profile attributes into directories called user pools that a mobile app or IoT devices uses to configure limited access to Tangle accelerator.

Functional Requirement:
* HTTPS protocol
* Password or access-token auth
* Log management

TODO:
* Solution Evaluation
  * [Amazon Cognito](https://aws.amazon.com/tw/cognito/)
    * [Amazon Cognito pricing](https://aws.amazon.com/tw/cognito/pricing/)
  * [ngx-oauth](https://github.com/jirutka/ngx-oauth)
* Deploy
  * Public access-token
    * Permission for public use: All APIs
    * upstream backend: nodeX.puyuma.org ~ nodeY.puyuma.org
  * Business access-token
     * Permission for public use: All APIs
     * upstream backend: nodeX.puyuma.org ~ nodeY.puyuma.org
  * Log management
    * Log file
    * Web report or dashboard
* Auth2
  * [OAuth 2.0 筆記 ](https://blog.yorkxin.org/2013/09/30/oauth2-1-introduction.html)

**Comment by yillkid** [comment]
We can use [iri-lb-haproxy](https://github.com/nuriel77/iri-lb-haproxy) as load balancer solution! Reading my [note](https://hackmd.io/s/B1VnrCj_X) for detail.

TODO:

* Full-node deploy plans
* Prometheus integration
* Tangle Accelerator integration

**Comment by yillkid** [comment]
nuriel77, the main contributor of [iri-lb-haproxy](https://github.com/nuriel77/iri-lb-haproxy) invite me to test the feature via the new iri/dockerized version.

This is the overview document: [https://iri-playbook.readthedocs.io/en/feat-docker/loadbalancer.html](https://iri-playbook.readthedocs.io/en/feat-docker/loadbalancer.html)
The quick installation steps are here: [https://iri-playbook.readthedocs.io/en/feat-docker/loadbalancer.html#quick-installation-example-for-multiple-nodes](https://iri-playbook.readthedocs.io/en/feat-docker/loadbalancer.html#quick-installation-example-for-multiple-nodes)

**Comment by jserv** [comment]
@yillkid, please make a comprehensive tickets regarding iri/dockerized and close this accordingly.

**Comment by yillkid** [comment]
The latest commit of [iri-lb-haproxy](https://github.com/nuriel77/iri-lb-haproxy) was 8 months ago and still have many [TODO](https://github.com/nuriel77/iri-lb-haproxy#todo) and issues.

My suggestion is change solution to [Nginx](http://nginx.org/en/docs/http/load_balancing.html), I have deploy a IOTA full-node load balancing service on node0:

- HOST
  - node0.puyuma.org:8002
- BACKEND
  - server node.deviceproof.org:443
  - server potato.iotasalad.org:14265
  - server durian.iotasalad.org:14265
  - server peanut.iotasalad.org:14265
  - server tuna.iotasalad.org:14265
  - server turnip.iotasalad.org:14265
- TODO
  - backend health check service

**Comment by jserv** [comment]
Let's deprecate `[iri-lb-haproxy` and concentrate on nginx approach. @yillkid, write down corresponding issues.
