### ISSUE TITLE
Tangle: DeviceProof getBalances API Internal Server Error

### ISSUE THREAD

**Issue by ender503** [DLTcollab/general#99]
Use the following command to request balances, will get the HTTP response with status code 500 (Internal Server Error).

```shell
$ curl -i https://node.deviceproof.org:443 \
  -X POST \
  -H 'Content-Type: application/json' \
  -H 'X-IOTA-API-Version: 1' \
  -d '{"command":"getBalances","addresses":["UJEXGZATBRLPSMYIJAMBGI9E99QUOQSTEQKXJSBXVC9GHGCHLPOJFZJBUKDDLTXGRH9FCPPNMUSAAXAGW"],"threshold":100}'
```

```shell
HTTP/1.1 500 Internal Server Error
Server: nginx/1.10.3 (Ubuntu)
Date: Wed, 10 Oct 2018 08:24:06 GMT
Content-Type: application/json
Content-Length: 14
Connection: keep-alive
Access-Control-Allow-Origin: *

{"duration":2}%
```

**Comment by ender503** [comment]
Thenode10.puyuma.org(mainnet) has the same problem.
It's weird and I can't figure out, here is the output from node10.

```shell
$ curl -i http://node10.puyuma.org:14265 \
  -X POST \
  -H 'Content-Type: application/json' \
  -H 'X-IOTA-API-Version: 1' \
  -d '{"command":"getBalances","addresses":["UJEXGZATBRLPSMYIJAMBGI9E99QUOQSTEQKXJSBXVC9GHGCHLPOJFZJBUKDDLTXGRH9FCPPNMUSAAXAGW"],"threshold":100}'
```

```shell
HTTP/1.1 500 Internal Server Error
Connection: keep-alive
Access-Control-Allow-Origin: *
Keep-Alive: timeout=500, max=100
Content-Type: application/json
Content-Length: 15
Date: Sat, 20 Oct 2018 10:48:00 GMT

{"duration":21}%
```

**Comment by ender503** [comment]
Since the response status code is 500, it's unused error.
The error exception is not generated by the `ErrorResponse.create()`. [Link](https://github.com/iotaledger/iri/blob/dev/src/main/java/com/iota/iri/service/API.java#L1170)

**Comment by jserv** [comment]
@yillkid, It is time to narrow down the problem. I have merged latest upstream `dev` to [our own IRI](https://github.com/DLTcollab/iri). Please check.
NOTE: you have to package without running tests. That is, `mvn package -Dmaven.test.skip=true`

**Comment by yillkid** [comment]
OK, upgrade finish on node10 and devorg, the nodes work fine ... I will begin to trace this issue after fully synced.

**Comment by jserv** [comment]
Solution confirmed.
